ALTER TABLE [dbo].[QRTZ_JOB_DATA_MAP] DROP CONSTRAINT [FK_QRTZ_JOB_DATA_MAP_QRTZ_JOB_DETAIL]
GO
ALTER TABLE [dbo].[QRTZ_JOB_LISTENERS] DROP CONSTRAINT [FK_QRTZ_JOB_LISTENERS_QRTZ_JOB_DETAILS]
GO
ALTER TABLE [dbo].[QRTZ_CRON_TRIGGERS] DROP CONSTRAINT [FK_QRTZ_CRON_TRIGGERS_QRTZ_TRIGGERS]
GO
ALTER TABLE [dbo].[QRTZ_SIMPLE_TRIGGERS] DROP CONSTRAINT [FK_QRTZ_SIMPLE_TRIGGERS_QRTZ_TRIGGERS]
GO
ALTER TABLE [dbo].[QRTZ_TRIGGER_LISTENERS] DROP CONSTRAINT [FK_QRTZ_TRIGGER_LISTENERS_QRTZ_TRIGGERS]
GO
ALTER TABLE [dbo].[QRTZ_TRIGGERS] DROP CONSTRAINT [FK_QRTZ_TRIGGERS_QRTZ_JOB_DETAILS]
GO
ALTER TABLE [dbo].[QRTZ_FIRED_TRIGGERS] DROP CONSTRAINT [PK_QRTZ_FIRED_TRIGGERS]
GO
ALTER TABLE [dbo].[QRTZ_JOB_LISTENERS] DROP CONSTRAINT [PK_QRTZ_JOB_LISTENERS]
GO
ALTER TABLE [dbo].[QRTZ_SIMPLE_TRIGGERS] DROP CONSTRAINT [PK_QRTZ_SIMPLE_TRIGGERS]
GO
ALTER TABLE [dbo].[QRTZ_TRIGGER_LISTENERS] DROP CONSTRAINT [PK_QRTZ_TRIGGER_LISTENERS]
GO
ALTER TABLE [dbo].[QRTZ_PAUSED_TRIGGER_GRPS] DROP CONSTRAINT [PK_QRTZ_PAUSED_TRIGGER_GRPS]
GO
ALTER TABLE [dbo].[QRTZ_SCHEDULER_STATE] DROP CONSTRAINT [PK_QRTZ_SCHEDULER_STATE]
GO
ALTER TABLE [dbo].[QRTZ_CALENDARS] DROP CONSTRAINT [PK_QRTZ_CALENDARS]
GO
ALTER TABLE [dbo].[QRTZ_CRON_TRIGGERS] DROP CONSTRAINT [PK_QRTZ_CRON_TRIGGERS]
GO
ALTER TABLE [dbo].[QRTZ_JOB_DETAILS] DROP CONSTRAINT [PK_QRTZ_JOB_DETAILS]
GO
ALTER TABLE [dbo].[QRTZ_TRIGGERS] DROP CONSTRAINT [PK_QRTZ_TRIGGERS]
GO
DROP INDEX [IDX_FIRED_TRIGGERS_NAME_GROUP] ON [dbo].[QRTZ_FIRED_TRIGGERS]
GO
ALTER TABLE [dbo].[QRTZ_TRIGGER_LISTENERS] ALTER COLUMN [TRIGGER_NAME] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
GO
ALTER TABLE [dbo].[QRTZ_BLOB_TRIGGERS] ALTER COLUMN [TRIGGER_GROUP] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
GO
ALTER TABLE [dbo].[QRTZ_TRIGGER_LISTENERS] ALTER COLUMN [TRIGGER_GROUP] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
GO
ALTER TABLE [dbo].[QRTZ_TRIGGER_LISTENERS] ALTER COLUMN [TRIGGER_LISTENER] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
GO
ALTER TABLE [dbo].[QRTZ_SCHEDULER_STATE] DROP COLUMN [RECOVERER]
GO
ALTER TABLE [dbo].[QRTZ_SCHEDULER_STATE] ALTER COLUMN [INSTANCE_NAME] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
GO
ALTER TABLE [dbo].[QRTZ_SIMPLE_TRIGGERS] ALTER COLUMN [TRIGGER_GROUP] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
GO
ALTER TABLE [dbo].[QRTZ_CALENDARS] ALTER COLUMN [CALENDAR_NAME] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
GO
ALTER TABLE [dbo].[QRTZ_TRIGGERS] ALTER COLUMN [CALENDAR_NAME] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
GO
ALTER TABLE [dbo].[QRTZ_TRIGGERS] ALTER COLUMN [DESCRIPTION] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
GO
ALTER TABLE [dbo].[QRTZ_CRON_TRIGGERS] ALTER COLUMN [CRON_EXPRESSION] [varchar] (120) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
GO
ALTER TABLE [dbo].[QRTZ_TRIGGERS] ADD 
[PRIORITY] [int] NULL,
[JOB_DATA] [image] NULL
GO
update [dbo].[QRTZ_TRIGGERS] set PRIORITY = 5 where PRIORITY IS NULL 
GO
ALTER TABLE [dbo].[QRTZ_TRIGGERS] ALTER COLUMN [JOB_GROUP] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
GO
ALTER TABLE [dbo].[QRTZ_TRIGGERS] ALTER COLUMN [TRIGGER_GROUP] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
GO
ALTER TABLE [dbo].[QRTZ_TRIGGERS] ALTER COLUMN [TRIGGER_NAME] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
GO
ALTER TABLE [dbo].[QRTZ_TRIGGERS] ALTER COLUMN [JOB_NAME] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
GO
ALTER TABLE [dbo].[QRTZ_BLOB_TRIGGERS] ALTER COLUMN [TRIGGER_NAME] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
GO
ALTER TABLE [dbo].[QRTZ_JOB_DETAILS] ALTER COLUMN [DESCRIPTION] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
GO
ALTER TABLE [dbo].[QRTZ_JOB_LISTENERS] ALTER COLUMN [JOB_NAME] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
GO
ALTER TABLE [dbo].[QRTZ_JOB_DETAILS] ALTER COLUMN [JOB_GROUP] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
GO
ALTER TABLE [dbo].[QRTZ_JOB_LISTENERS] ALTER COLUMN [JOB_GROUP] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
GO
ALTER TABLE [dbo].[QRTZ_JOB_DETAILS] ALTER COLUMN [JOB_CLASS_NAME] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
GO
ALTER TABLE [dbo].[QRTZ_JOB_LISTENERS] ALTER COLUMN [JOB_LISTENER] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
GO
ALTER TABLE [dbo].[QRTZ_JOB_DETAILS] ALTER COLUMN [JOB_NAME] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
GO
ALTER TABLE [dbo].[QRTZ_PAUSED_TRIGGER_GRPS] ALTER COLUMN [TRIGGER_GROUP] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
GO
ALTER TABLE [dbo].[QRTZ_CRON_TRIGGERS] ALTER COLUMN [TRIGGER_GROUP] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
GO
ALTER TABLE [dbo].[QRTZ_CRON_TRIGGERS] ALTER COLUMN [TRIGGER_NAME] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
GO
ALTER TABLE [dbo].[QRTZ_JOB_DETAILS] ADD 
[JOB_DATA] [image] NULL
GO
ALTER TABLE [dbo].[QRTZ_SIMPLE_TRIGGERS] ALTER COLUMN [TRIGGER_NAME] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
GO
CREATE TABLE [dbo].[TempQRTZ_FIRED_TRIGGERS]
(
	[ENTRY_ID] [varchar] (95) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[TRIGGER_NAME] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[TRIGGER_GROUP] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[IS_VOLATILE] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[INSTANCE_NAME] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[FIRED_TIME] [bigint] NOT NULL,
	[PRIORITY] [int] NOT NULL,
	[STATE] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[JOB_NAME] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[JOB_GROUP] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IS_STATEFUL] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REQUESTS_RECOVERY] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL

) ON [PRIMARY]
GO

INSERT INTO [dbo].[TempQRTZ_FIRED_TRIGGERS] ([ENTRY_ID],[TRIGGER_NAME],[TRIGGER_GROUP],[IS_VOLATILE],[INSTANCE_NAME],[FIRED_TIME],[STATE],[JOB_NAME],[JOB_GROUP],[IS_STATEFUL],[REQUESTS_RECOVERY],[PRIORITY]) SELECT [ENTRY_ID],[TRIGGER_NAME],[TRIGGER_GROUP],[IS_VOLATILE],[INSTANCE_NAME],[FIRED_TIME],[STATE],[JOB_NAME],[JOB_GROUP],[IS_STATEFUL],[REQUESTS_RECOVERY],5 FROM [dbo].[QRTZ_FIRED_TRIGGERS]
DROP TABLE [dbo].[QRTZ_FIRED_TRIGGERS]
GO
EXEC sp_rename N'[dbo].[TempQRTZ_FIRED_TRIGGERS]',N'QRTZ_FIRED_TRIGGERS', 'OBJECT'
GO


ALTER TABLE [dbo].[QRTZ_JOB_LISTENERS] ADD CONSTRAINT [PK_QRTZ_JOB_LISTENERS] PRIMARY KEY CLUSTERED
	(
		[JOB_NAME] ASC,
		[JOB_GROUP] ASC,
		[JOB_LISTENER] ASC
	) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[QRTZ_FIRED_TRIGGERS] ADD CONSTRAINT [PK_QRTZ_FIRED_TRIGGERS] PRIMARY KEY CLUSTERED
	(
		[ENTRY_ID] ASC
	) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[QRTZ_CALENDARS] ADD CONSTRAINT [PK_QRTZ_CALENDARS] PRIMARY KEY CLUSTERED
	(
		[CALENDAR_NAME] ASC
	) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[QRTZ_PAUSED_TRIGGER_GRPS] ADD CONSTRAINT [PK_QRTZ_PAUSED_TRIGGER_GRPS] PRIMARY KEY CLUSTERED
	(
		[TRIGGER_GROUP] ASC
	) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[QRTZ_TRIGGER_LISTENERS] ADD CONSTRAINT [PK_QRTZ_TRIGGER_LISTENERS] PRIMARY KEY CLUSTERED
	(
		[TRIGGER_NAME] ASC,
		[TRIGGER_GROUP] ASC,
		[TRIGGER_LISTENER] ASC
	) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[QRTZ_CRON_TRIGGERS] ADD CONSTRAINT [PK_QRTZ_CRON_TRIGGERS] PRIMARY KEY CLUSTERED
	(
		[TRIGGER_NAME] ASC,
		[TRIGGER_GROUP] ASC
	) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[QRTZ_SIMPLE_TRIGGERS] ADD CONSTRAINT [PK_QRTZ_SIMPLE_TRIGGERS] PRIMARY KEY CLUSTERED
	(
		[TRIGGER_NAME] ASC,
		[TRIGGER_GROUP] ASC
	) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[QRTZ_SCHEDULER_STATE] ADD CONSTRAINT [PK_QRTZ_SCHEDULER_STATE] PRIMARY KEY CLUSTERED
	(
		[INSTANCE_NAME] ASC
	) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[QRTZ_JOB_DETAILS] ADD CONSTRAINT [PK_QRTZ_JOB_DETAILS] PRIMARY KEY CLUSTERED
	(
		[JOB_NAME] ASC,
		[JOB_GROUP] ASC
	) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[QRTZ_TRIGGERS] ADD CONSTRAINT [PK_QRTZ_TRIGGERS] PRIMARY KEY CLUSTERED
	(
		[TRIGGER_NAME] ASC,
		[TRIGGER_GROUP] ASC
	) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[QRTZ_CRON_TRIGGERS] ADD CONSTRAINT [FK_QRTZ_CRON_TRIGGERS_QRTZ_TRIGGERS] FOREIGN KEY
	(
		[TRIGGER_NAME],
		[TRIGGER_GROUP]
	)
	REFERENCES [dbo].[QRTZ_TRIGGERS]
	(
		[TRIGGER_NAME],
		[TRIGGER_GROUP]
	) ON DELETE CASCADE
GO
ALTER TABLE [dbo].[QRTZ_SIMPLE_TRIGGERS] ADD CONSTRAINT [FK_QRTZ_SIMPLE_TRIGGERS_QRTZ_TRIGGERS] FOREIGN KEY
	(
		[TRIGGER_NAME],
		[TRIGGER_GROUP]
	)
	REFERENCES [dbo].[QRTZ_TRIGGERS]
	(
		[TRIGGER_NAME],
		[TRIGGER_GROUP]
	) ON DELETE CASCADE
GO
ALTER TABLE [dbo].[QRTZ_TRIGGER_LISTENERS] ADD CONSTRAINT [FK_QRTZ_TRIGGER_LISTENERS_QRTZ_TRIGGERS] FOREIGN KEY
	(
		[TRIGGER_NAME],
		[TRIGGER_GROUP]
	)
	REFERENCES [dbo].[QRTZ_TRIGGERS]
	(
		[TRIGGER_NAME],
		[TRIGGER_GROUP]
	) ON DELETE CASCADE
GO
ALTER TABLE [dbo].[QRTZ_JOB_LISTENERS] ADD CONSTRAINT [FK_QRTZ_JOB_LISTENERS_QRTZ_JOB_DETAILS] FOREIGN KEY
	(
		[JOB_NAME],
		[JOB_GROUP]
	)
	REFERENCES [dbo].[QRTZ_JOB_DETAILS]
	(
		[JOB_NAME],
		[JOB_GROUP]
	) ON DELETE CASCADE
GO
ALTER TABLE [dbo].[QRTZ_TRIGGERS] ADD CONSTRAINT [FK_QRTZ_TRIGGERS_QRTZ_JOB_DETAILS] FOREIGN KEY
	(
		[JOB_NAME],
		[JOB_GROUP]
	)
	REFERENCES [dbo].[QRTZ_JOB_DETAILS]
	(
		[JOB_NAME],
		[JOB_GROUP]
	)
GO
create index idx_qrtz_ft_trig_n_g on qrtz_fired_triggers(TRIGGER_NAME,TRIGGER_GROUP);
create index idx_qrtz_ft_trig_inst_name on qrtz_fired_triggers(INSTANCE_NAME);
create index idx_qrtz_ft_job_name on qrtz_fired_triggers(JOB_NAME);
create index idx_qrtz_ft_job_group on qrtz_fired_triggers(JOB_GROUP);
GO
