update current_version set systype = 'kms'
	
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.add.link_requests','Link Articles')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.admin.volunteer','Volunteer')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.all.camel_case_request','Article')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.myrequests.subscriber','Subscriber')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.view.update_request','Update Article')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.view.transfer_request','Transfer Article')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.all.camel_case_requests','Articles')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.all.request_type','Article Type')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.view.sort_request_history','Sort Article History')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.all.my_requests','My Articles')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.main.all.request_number','Article #')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.myrequests.logger','Author')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.all.request','article')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.view.request_history','Article History')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.view.add_subrequest','Add Subarticle')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.view.add_request','Add Article')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.definition','Knowledge Management System')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.view.print_request_details','Print Article Details')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.description','tBits is the next generation web-based knowledge management system that combines the power of workflow, database systems, advance searching technology and convenience of email systems.')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.myrequests.due_date','Review Date')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.admin.assignee','Reviewer')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.all.requests','articles')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.view.request_details','Article Details')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.all.camel_case_severity','Priority')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.myrequests.assignee','Reviewer')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.view.subrequests','Subarticles')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.all.new_request','New Article')
INSERT INTO captions_properties(sys_id,name,value) Values(0,'captions.all.my_reports', 'My Reports')
INSERT INTO captions_properties(sys_id,name,value) Values(0,'captions.view.update_summary', 'Update Summary')
INSERT INTO captions_properties(sys_id,name,value) Values(0,'captions.view.add_summary', 'Add Summary')

GO
