update current_version set systype = 'request'
	
INSERT INTO captions_properties(sys_id,name,value) Values(0,'captions.view.transfer_request','Transfer Request')
INSERT INTO captions_properties(sys_id,name,value) Values(0,'captions.all.camel_case_request','Request')
INSERT INTO captions_properties(sys_id,name,value) Values(0,'captions.all.camel_case_requests','Requests')
INSERT INTO captions_properties(sys_id,name,value) Values(0,'captions.myrequests.subscriber','Subscriber')
INSERT INTO captions_properties(sys_id,name,value) Values(0,'captions.all.request_type','Request Type')
INSERT INTO captions_properties(sys_id,name,value) Values(0,'captions.view.add_request','Add Request')
INSERT INTO captions_properties(sys_id,name,value) Values(0,'captions.view.print_request_details','Print Request Details')
INSERT INTO captions_properties(sys_id,name,value) Values(0,'captions.description','tBits is the next generation web-based issue tracking system that combines the power of workflow, database systems, advance searching technology and convenience of email systems.')
INSERT INTO captions_properties(sys_id,name,value) Values(0,'captions.add.link_requests','Link Requests')
INSERT INTO captions_properties(sys_id,name,value) Values(0,'captions.admin.assignee','Assignee')
INSERT INTO captions_properties(sys_id,name,value) Values(0,'captions.myrequests.logger','Logger')
INSERT INTO captions_properties(sys_id,name,value) Values(0,'captions.admin.volunteer','Volunteer')
INSERT INTO captions_properties(sys_id,name,value) Values(0,'captions.view.add_subrequest','Add Subrequest')
INSERT INTO captions_properties(sys_id,name,value) Values(0,'captions.all.new_request','New Request')
INSERT INTO captions_properties(sys_id,name,value) Values(0,'captions.main.all.request_number','Request #')
INSERT INTO captions_properties(sys_id,name,value) Values(0,'captions.all.request','request')
INSERT INTO captions_properties(sys_id,name,value) Values(0,'captions.definition','Issue tracking System')
INSERT INTO captions_properties(sys_id,name,value) Values(0,'captions.view.request_details','Request Details')
INSERT INTO captions_properties(sys_id,name,value) Values(0,'captions.all.my_requests','My Requests')
INSERT INTO captions_properties(sys_id,name,value) Values(0,'captions.view.request_history','Request History')
INSERT INTO captions_properties(sys_id,name,value) Values(0,'captions.view.update_request','Update Request')
INSERT INTO captions_properties(sys_id,name,value) Values(0,'captions.myrequests.due_date','Due Date')
INSERT INTO captions_properties(sys_id,name,value) Values(0,'captions.all.camel_case_severity','Priority')
INSERT INTO captions_properties(sys_id,name,value) Values(0,'captions.view.sort_request_history','Sort Request History')
INSERT INTO captions_properties(sys_id,name,value) Values(0,'captions.view.subrequests','Subrequests')
INSERT INTO captions_properties(sys_id,name,value) Values(0,'captions.all.requests','requests')
INSERT INTO captions_properties(sys_id,name,value) Values(0,'captions.myrequests.assignee','Assignee')
INSERT INTO captions_properties(sys_id,name,value) Values(0,'captions.all.my_reports', 'My Reports')
INSERT INTO captions_properties(sys_id,name,value) Values(0,'captions.view.update_summary', 'Update Summary')
INSERT INTO captions_properties(sys_id,name,value) Values(0,'captions.view.add_summary', 'Add Summary')
GO