/*
 * Copyright (c) 2005 Transbit Technologies Pvt. Ltd. All rights reserved.
 *
 * This software is the confidential and proprietary information
 * of Transbit Technologies Pvt. Ltd. ("Confidential Information").  You
 * shall not disclose such Confidential Information and shall use
 * it only in accordance with the terms of the license agreement
 * you entered into with Transbit Technologies Pvt. Ltd.
 */



/* Generated By:JavaCC: Do not edit this line. TBitsTokenizerConstants.java */

/**
 * TBitsTokenizer.java
 *
 * $Header:
 */
package transbit.tbits.indexer;

public interface TBitsTokenizerConstants {
    int      EOF        = 0;
    int      EMAIL      = 5;
    int      COMPANY    = 4;
    int      APOSTROPHE = 2;
    int      ALPHANUM   = 1;
    int      ACRONYM    = 3;
    int      HOST       = 6;
    int      PERLMOD    = 7;
    int      SMARTLINK  = 8;
    int      P          = 11;
    int      NUM        = 10;
    int      NOISE      = 17;
    int      LETTER     = 14;
    int      HAS_DIGIT  = 12;
    int      FILENAME   = 9;
    int      DIGIT      = 16;
    int      DEFAULT    = 0;
    int      CJK        = 15;
    int      ALPHA      = 13;
    String[] tokenImage = {
        "<EOF>", "<ALPHANUM>", "<APOSTROPHE>", "<ACRONYM>", "<COMPANY>", "<EMAIL>", "<HOST>", "<PERLMOD>", "<SMARTLINK>", "<FILENAME>", "<NUM>", "<P>", "<HAS_DIGIT>", "<ALPHA>", "<LETTER>", "<CJK>",
        "<DIGIT>", "<NOISE>",
    };
}
