package ksksco;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.HashMap;
import java.util.Hashtable;

import transbit.tbits.api.AttachmentInfo;
import transbit.tbits.domain.BusinessArea;
import transbit.tbits.domain.Field;
import transbit.tbits.domain.Permission;
import transbit.tbits.exception.TBitsException;

import org.eclipse.birt.report.engine.api.EngineConfig;
import org.eclipse.birt.report.engine.api.EngineException;
import org.eclipse.birt.report.engine.api.IReportDocument;
import org.eclipse.birt.report.engine.api.IReportEngine;
import org.eclipse.birt.report.engine.api.IReportRunnable;
import org.eclipse.birt.report.model.api.activity.SemanticException;

import transbit.tbits.common.TBitsLogger;
import transbit.tbits.report.TBitsReportEngine;

import com.google.gson.JsonObject;
import com.google.gson.JsonParser;

public class scoConstants {
	
public static final String SCO_sysprefix="SCO"; // BA
public static final String SCO_Business_Area="sys_id";	
public static final String SCO_Request="request_id";	
public static final String SCO_Category="category_id";	// Department Codes
public static final String SCO_Status="status_id";	
public static final String SCO_Priority="severity_id";	
public static final String SCO_Contract_Type="request_type_id";	
public static final String SCO_Logger="logger_ids";	
public static final String SCO_Assignee="assignee_ids";	
public static final String SCO_Subscribers="subscriber_ids";	
public static final String SCO_To="to_ids";	
public static final String SCO_Cc="cc_ids";	
public static final String SCO_Subject="subject";	
public static final String SCO_Description="description";	
public static final String SCO_Private="is_private";	
public static final String SCO_Parent="parent_request_id";	
public static final String SCO_Last_Update_By_="user_id";	
public static final String SCO___U="max_action_id";	
public static final String SCO_Due_Date="due_datetime";	
public static final String SCO_Submitted_Date="logged_datetime";	
public static final String SCO_Last_Updated="lastupdated_datetime";	
public static final String SCO_Header_Description="header_description";	
public static final String SCO_Attachments="attachments";	
public static final String SCO_Summary="summary";	
public static final String SCO_Memo="memo";	
public static final String SCO_append_interface="append_interface";	
public static final String SCO_Notify="notify";	
public static final String SCO_Notify_Logger="notify_loggers";	
public static final String SCO_replied_to_action="replied_to_action";	
public static final String SCO_Linked_Requests="related_requests";	
public static final String SCO_Office="office_id";	
public static final String SCO_Send_SMS="SendSMS";	
public static final String SCO_SCO_Order__="SCONo";	// Unique SCO Order No 
public static final String SCO_SCO_Date="SCODate";	
public static final String SCO_Drawings_Affected="Drawings";	
public static final String SCO_System_Affected="Systems";	
public static final String SCO_Exp_Value_Change__Rs_="ExpValueChange";	
public static final String SCO_Actual_Value_Change__Rs_="ActualValueChange";	
public static final String SCO_Exp_Time_Change="ExpectedTimeChange";	
public static final String SCO_Actual_Time_Change="ActualTimeChange";	
public static final String SCO_Original_Clause="OriginalClause";	
public static final String SCO_Proposed_Clause="ProposedClause";	
public static final String SCO_Other_Implications="OtherImplications";	
public static final String SCO_Affected_Clauses="AffectedClauses";	
public static final String SCO_Actual_Value_Change__USD_="ActualValueChangeUSD";	
public static final String SCO_Exp_Value_Change__USD_="ExpValueChangeUSD";	
public static final String SCO_Intiated_By="intiatedby";	
public static final String SCO_Unit_Code="unitcode"; // Unit Code
public static final String SCO_SCO_File="SCOFile";
public static final String SCO_GENERATION_AGENCY = "GenerationAgency"; // Generated by
public static final String SCO_STATUS_TYPE_ACCEPTED = "Accepted";
public static final String SCO_STATUS_TYPE_REJECTED = "Rejected";
public static final String SCO_STATUS_TYPE_SUSPENDED = "Suspended";
public static final String SCO_ORIGINAL_SCHEDULE = "orginalScheduleType";
public static final String SCO_PROPOSED_SCHEDULE = "proposedScheduleType";
public static final String SCO_ORIGINAL_CURRENCY = "currencyOC";
public static final String SCO_PROPOSED_CURRENCY = "currencyPC";
public static final String SCO_GENERATE_SCOPDF = "generateSCOpdf";

public static final int SCO_DUEDATE_DURATION = 30;
public static final String USER_LOGIN_GPRAO = "gprao";
public static final String USER_LOGIN_KIRANPANDA = "kiranpanda";
public static final String USER_LOGIN_XUELI = "xueli";
public static final String TBITS_ROOT="root";



public static final String CORR_sysprefix="CORR";
public static final String CORR_Business_Area="sys_id";
public static final String CORR_Request="request_id";
public static final String CORR_Communication_Protocol="category_id";
public static final String CORR_Originator="status_id";
public static final String CORR_Corr__Type="severity_id";
public static final String CORR_Corr_Status="request_type_id";
public static final String CORR_Logger="logger_ids";
public static final String CORR_Assignee="assignee_ids";
public static final String CORR_Subscribers="subscriber_ids";
public static final String CORR_To="to_ids";
public static final String CORR_Cc="cc_ids";
public static final String CORR_Subject="subject";
public static final String CORR_Description="description";
public static final String CORR_Private="is_private";
public static final String CORR_Parent="parent_request_id";
public static final String CORR_Last_Update_By_="user_id";
public static final String CORR___U="max_action_id";
public static final String CORR_Due_Date="due_datetime";
public static final String CORR_Submitted_Date="logged_datetime";
public static final String CORR_Last_Updated="lastupdated_datetime";
public static final String CORR_Header_Description="header_description";
public static final String CORR_Other_Attachments="attachments";
public static final String CORR_Summary="summary";
public static final String CORR_Memo="memo";
public static final String CORR_append_interface="append_interface";
public static final String CORR_Notify="notify";
public static final String CORR_Notify_Logger="notify_loggers";
public static final String CORR_replied_to_action="replied_to_action";
public static final String CORR_Linked_Requests="related_requests";
public static final String CORR_Office="office_id";
public static final String CORR_Send_SMS="SendSMS";
public static final String CORR_SMS_Id="sms_id";
public static final String CORR_Correspondence_File="CorrespondanceFile";
public static final String CORR_Generate_Correspondance="GenerateCorrespondance";
public static final String CORR_Generation_Agency="CorrGenerationAgency";
public static final String CORR_Correspondence_Number="CorrespondanceNumber";
public static final String CORR_Int_WPCL_Circulation="InternalWPCLCirculationList";
public static final String CORR_Thread_Id="threadid";
public static final String CORR_Drafted_By="DraftedBy";
public static final String CORR_Checked_By="CheckedBy";
public static final String CORR_Source_Requests="SourceRequests";

public static final String SCO_REP_INITIATEDBY				= "initiatedBy";
public static final String SCO_REP_SCO_NO					= "scoNo";
public static final String SCO_REP_SCODATE					= "scoDate";
public static final String SCO_REP_DRAWINGNO				= "drwNo";
public static final String SCO_REP_EQUIPMENT				= "equipment"; // systems affected
public static final String SCO_REP_OSCOPE_DESC				= "originalScopeDescripation";
public static final String SCO_REP_PCSCOPE_DESC				= "pcScopeDesription";
public static final String SCO_REP_OSCOPE_ADJCONTRCT_VAL	= "osAdjustmentContractValue";
public static final String SCO_REP_PCSCOPE_ADJCONTRCT_VAL	= "pcAdjustmentContractValue";
public static final String SCO_REP_OSCOPE_ADJPROJECT_SCH	= "osAdjustmentProjectschedule";
public static final String SCO_REP_PCSCOPE_ADJPROJECT_SCH	= "pcAdjustmentProjectschedule";
public static final String SCO_REP_OTHERIMPLCT				= "otherImplications";
public static final String SCO_REP_CNCTR_PROPSLDATE			= "contractorProposalDate";
public static final String SCO_REP_OWNR_APPRVLDATE			= "ownerApprovalDate";
public static final String SCO_REP_IMAGEPATH				= "ImagePath"; //Default ImagePath = "tbitsreport/ganesh.gif";

public static final String REP_RID = "rid";
public static final String REP_TBITS_BASE_URL_KEY = "tbits_base_url";

public static final TBitsLogger LOG = TBitsLogger.getLogger("kskSCO");


public static JsonObject getAttachmentJson(BusinessArea businessArea,Hashtable<String, Integer> permissions, Hashtable<Field,ArrayList<AttachmentInfo>> attachTable)
{
    JsonObject rootNode = new JsonObject();
    JsonParser jsonParser = new JsonParser();
    for(Enumeration<Field> fields = attachTable.keys() ; fields.hasMoreElements() ;)
    {
            Field f = fields.nextElement() ;
            Integer fieldPermInteger = permissions.get(f.getName());
            int fieldPerm = 0;
            if(fieldPermInteger != null)
                fieldPerm = fieldPermInteger.intValue();
            
            if( (fieldPerm & Permission.VIEW) != 0)
            {
                Boolean canChange = ( (fieldPerm & Permission.CHANGE) != 0);
                Boolean canAdd = ( (fieldPerm & Permission.ADD) != 0);
                JsonObject fieldNode = new JsonObject();
                fieldNode.addProperty("fieldDisplayName", f.getDisplayName());
                fieldNode.addProperty("canChange", canChange);
                fieldNode.addProperty("canAdd", canAdd);
                fieldNode.addProperty("displayOder", f.getDisplayOrder());
                fieldNode.addProperty("fieldId", f.getFieldId());
                fieldNode.addProperty("numberOfFiles", 0);
                String filesStr = null;
                
                if (attachTable != null) 
                {
                    ArrayList<AttachmentInfo> attInfo = attachTable.get(f) ;                           
                    filesStr = AttachmentInfo.toJson(attInfo);                     
                }
                
                if( (filesStr == null) || (filesStr.trim().length() == 0))
                    filesStr = "[]";
                
                fieldNode.add("files", jsonParser.parse(filesStr));
                rootNode.add(f.getName(), fieldNode);
          }
    }
    return rootNode;
}

	// Function to generate pdf report for SCO by BIRT Engine.
	public static File generateReport( String reportName, Hashtable<String, String> params,
			HashMap<String, String> reportParams, String format ) throws TBitsException, IOException{
		
		IReportDocument ird			= null ; // Birt
		TBitsReportEngine tre		= null ; // tBits
		
		try {
			
			tre = TBitsReportEngine.getInstance();
			if(tre == null){
				LOG.error("Unable to get the instance of ReportEngine.");
				return null ;
			}
			
			IReportRunnable reportDesign; // Birt
			reportDesign = tre.getReportDesign(reportName);
			if(reportDesign == null){
				LOG.error("Unable to get the design instance of " + reportName);
				return null ;
			}
							
			ird = tre.getReportDocument(reportDesign, reportParams) ;
			
			File outFile = null ;
			if( format.trim().equalsIgnoreCase("pdf"))
			 outFile = tre.getPDFReport(ird);
			else 
				outFile = tre.getHTMLReport(ird) ; // default
			
			// print file info
			if( outFile != null ) 
			{
				System.out.println( "Name:" + outFile.getName() + " path = " + outFile.getAbsolutePath() ) ;
				return outFile ;
			}
			else
			{
				LOG.error("OutPUT file is null" ) ;
				return null ;
			}
						
		}
		catch (EngineException e) {
			e.printStackTrace();
			return null;
		}
		
		catch (IllegalArgumentException e) {
			e.printStackTrace();
			return null;
		}		
		
					
	}


}
