
INSERT INTO tbits_properties(name,value) Values('transbit.app.version','6.0.32.2640')
INSERT INTO tbits_properties(name,value) Values('transbit.tbits.instanceList','india,us')
INSERT INTO tbits_properties(name,value) Values('transbit.tbits.intenet.proxypassword','proxypassword')
INSERT INTO tbits_properties(name,value) Values('transbit.tbits.extract','bin/xls2csv.exe')
INSERT INTO tbits_properties(name,value) Values('transbit.tbits.smtp.authenticate','n')
INSERT INTO tbits_properties(name,value) Values('transbit.tbits.smtp.port','465')
INSERT INTO tbits_properties(name,value) Values('transbit.tbits.isautovueenabled','true  ')
INSERT INTO tbits_properties(name,value) Values('transbit.tbits.nearestInstance','http://localhost:80')
INSERT INTO tbits_properties(name,value) Values('mail.pop3s.socketFactory.fallback','false')
INSERT INTO tbits_properties(name,value) Values('transbit.tbits.jvueserver','http://localhost:5098/servlet/VueServlet')
INSERT INTO tbits_properties(name,value) Values('transbit.tbits.adContactSearchQuery','(&(objectCategory=person)(objectClass=contact))')
INSERT INTO tbits_properties(name,value) Values('transbit.tbits.pdftotext','bin/pdftotext.exe')
INSERT INTO tbits_properties(name,value) Values('transbit.tbits.sms.UserAgent','Firefox/2.0.0.11')
INSERT INTO tbits_properties(name,value) Values('transbit.tbits.adGroupSearchQuery','(&(objectCategory=Group)(objectClass=group))')
INSERT INTO tbits_properties(name,value) Values('transbit.tbits.hydUrl','http://localhost:80')
INSERT INTO tbits_properties(name,value) Values('transbit.tbits.allowAutoAddUser','true')
INSERT INTO tbits_properties(name,value) Values('transbit.tbits.smtp.protocol','smtp')
INSERT INTO tbits_properties(name,value) Values('transbit.tbits.smsgatewayurl','http://api.znisms.com/post/message.asp?userid=sandeepgiri&pwd=****&messageid=$MESSAGE$&senderid=sandeepgiri&sendto=$CELLNO$&flash=no')
INSERT INTO tbits_properties(name,value) Values('transbit.tbits.intenet.proxyuser','proxyuser')
INSERT INTO tbits_properties(name,value) Values('transbit.tbits.intenet.isproxyenabled','false')
INSERT INTO tbits_properties(name,value) Values('mail.pop3s.connectiontimeout','600000')
INSERT INTO tbits_properties(name,value) Values('transbit.tbits.logdir','logs')
INSERT INTO tbits_properties(name,value) Values('transbit.logger.notifyFailureTo','root@snowwhite.mshome.net')
INSERT INTO tbits_properties(name,value) Values('transbit.tbits.adSearchBase','CN=Users,DC=ABHISHEK,DC=com')
INSERT INTO tbits_properties(name,value) Values('transbit.tbits.adHost','ldap://transbit2000')
INSERT INTO tbits_properties(name,value) Values('transbit.tbits.intenet.proxyport','3128')
INSERT INTO tbits_properties(name,value) Values('mail.smtps.socketFactory.fallback','false')
INSERT INTO tbits_properties(name,value) Values('transbit.tbits.transmittal','false')
INSERT INTO tbits_properties(name,value) Values('transbit.logger.notifyFailureFrom','tbits@transbittech.com ')
INSERT INTO tbits_properties(name,value) Values('transbit.tbits.intenet.proxyserver','myproxyservername')
INSERT INTO tbits_properties(name,value) Values('transbit.tbits.smtp.password','san1deep')
INSERT INTO tbits_properties(name,value) Values('transbit.tbits.attachmentdir','attachments')
INSERT INTO tbits_properties(name,value) Values('transbit.tbits.smtp.isdebug','true')
INSERT INTO tbits_properties(name,value) Values('mail.pop3.timeout','600000')
INSERT INTO tbits_properties(name,value) Values('transbit.tbits.sms.enabled','false')
INSERT INTO tbits_properties(name,value) Values('transbit.tbits.myDomain','hyd')
INSERT INTO tbits_properties(name,value) Values('transbit.tbits.severityimgs','critical/+critical;critical.gif;Critical,high/+high;high.gif;High,low/+low;critical.gif;Low,very-low/very low/+very-low/+very low;v-low.gif;Very low"')
INSERT INTO tbits_properties(name,value) Values('transbit.tbits.redirectionURL','http://localhost:80')
INSERT INTO tbits_properties(name,value) Values('transbit.tbits.indexdir','index')
INSERT INTO tbits_properties(name,value) Values('transbit.tbits.responsepattern','^Message Sent..Success:.+')
INSERT INTO tbits_properties(name,value) Values('transbit.tbits.tmpdir','tmp')
INSERT INTO tbits_properties(name,value) Values('transbit.tbits.includeRecipients','true')
INSERT INTO tbits_properties(name,value) Values('transbit.tbits.antiword','bin/antiword.exe')
INSERT INTO tbits_properties(name,value) Values('transbit.tbits.ntlmEnabled','true')
INSERT INTO tbits_properties(name,value) Values('mail.smtps.socketFactory.class','transbit.tbits.mail.DummySSLSocketFactory')
INSERT INTO tbits_properties(name,value) Values('transbit.app.name','tBits')
INSERT INTO tbits_properties(name,value) Values('transbit.tbits.sendmail','${build.transbit.tbits.sendmail}')
INSERT INTO tbits_properties(name,value) Values('transbit.tbits.jvuecodebase','http://localhost/jVue')
INSERT INTO tbits_properties(name,value) Values('transbit.tbits.smtp.login','sandeep')
INSERT INTO tbits_properties(name,value) Values('transbit.tbits.smtp.server','localhost')
INSERT INTO tbits_properties(name,value) Values('mail.pop3.connectiontimeout','600000')
INSERT INTO tbits_properties(name,value) Values('transbit.tbits.adUserSearchQuery','(&(objectCategory=person)(objectClass=user))')
INSERT INTO tbits_properties(name,value) Values('mail.pop3s.socketFactory.class','transbit.tbits.mail.DummySSLSocketFactory')
INSERT INTO tbits_properties(name,value) Values('transbit.tbits.nycUrl','http://localhost:80')
INSERT INTO tbits_properties(name,value) Values('mail.pop3s.timeout','600000')
INSERT INTO tbits_properties(name,value) Values('transbit.tbits.auth.sessionMaxAge','31536000')


GO
SET ANSI_PADDING OFF

GO

INSERT INTO log4j_conf(name,value) Values('log4j.appender.INDEX.layout','org.apache.log4j.PatternLayout')
INSERT INTO log4j_conf(name,value) Values('log4j.logger.org.apache','INFO, ORG')
INSERT INTO log4j_conf(name,value) Values('log4j.logger.org.quartz','INFO,SCHED')
INSERT INTO log4j_conf(name,value) Values('log4j.appender.aWeb.layout','org.apache.log4j.PatternLayout')
INSERT INTO log4j_conf(name,value) Values('log4j.appender.aTest.layout.ConversionPattern','[ %d [%t] %C{2}.%M():%L %x %-5p]: %m%n')
INSERT INTO log4j_conf(name,value) Values('log4j.appender.ORG.layout.ConversionPattern','[ %d [%t] %C{2}.%M():%L %x %-5p]: %m%n')
INSERT INTO log4j_conf(name,value) Values('log4j.appender.aEmail','transbit.tbits.common.TBitsFileAppender')
INSERT INTO log4j_conf(name,value) Values('log4j.appender.aTest.layout','org.apache.log4j.PatternLayout')
INSERT INTO log4j_conf(name,value) Values('log4j.maillevel','OFF')
INSERT INTO log4j_conf(name,value) Values('log4j.ConversionPattern','[ %d [%t] %C{2}.%M():%L %x %-5p]: %m%n')
INSERT INTO log4j_conf(name,value) Values('log4j.appender.INDEX.File','${tbits.home}/logs/aIndex.log')
INSERT INTO log4j_conf(name,value) Values('log4j.appender.INDEX.layout.ConversionPattern','[ %d [%t] %C{2}.%M():%L %x %-5p]: %m%n')
INSERT INTO log4j_conf(name,value) Values('log4j.logger.net','INFO, ORG')
INSERT INTO log4j_conf(name,value) Values('log4j.logger.indexer','INFO,INDEX')
INSERT INTO log4j_conf(name,value) Values('log4j.appender.SCHED','transbit.tbits.common.TBitsFileAppender')
INSERT INTO log4j_conf(name,value) Values('log4j.appender.aCmdline.layout','org.apache.log4j.PatternLayout')
INSERT INTO log4j_conf(name,value) Values('log4j.rootLogger','INFO')
INSERT INTO log4j_conf(name,value) Values('log4j.logger.email','INFO,aEmail')
INSERT INTO log4j_conf(name,value) Values('log4j.logger.web','INFO,aWeb')
INSERT INTO log4j_conf(name,value) Values('log4j.appender.aCmdline.File','${tbits.home}/logs/aCmdLine.log')
INSERT INTO log4j_conf(name,value) Values('log4j.appender.SCHED.layout.ConversionPattern','[ %d [%t] %C{2}.%M():%L %x %-5p]: %m%n')
INSERT INTO log4j_conf(name,value) Values('log4j.appender.aEmail.layout','org.apache.log4j.PatternLayout')
INSERT INTO log4j_conf(name,value) Values('log4j.appender.ORG','transbit.tbits.common.TBitsAppender')
INSERT INTO log4j_conf(name,value) Values('log4j.appender.aEmail.File','${tbits.home}/logs/aEmail.log')
INSERT INTO log4j_conf(name,value) Values('log4j.logger.test','INFO,aTest')
INSERT INTO log4j_conf(name,value) Values('log4j.appender.aWeb','transbit.tbits.common.TBitsAppender')
INSERT INTO log4j_conf(name,value) Values('log4j.logger.cmdline','INFO, aCmdline')
INSERT INTO log4j_conf(name,value) Values('log4j.logger.cmdline.transbit.tbits.util','INFO,SCHED')
INSERT INTO log4j_conf(name,value) Values('log4j.appender.SCHED.File','${tbits.home}/logs/aSched.log')
INSERT INTO log4j_conf(name,value) Values('log4j.appender.aTest','transbit.tbits.common.TBitsAppender')
INSERT INTO log4j_conf(name,value) Values('log4j.appender.aEmail.layout.ConversionPattern','[ %d [%t] %C{2}.%M():%L %x %-5p]: %m%n')
INSERT INTO log4j_conf(name,value) Values('log4j.appender.aCmdline','transbit.tbits.common.TBitsFileAppender')
INSERT INTO log4j_conf(name,value) Values('log4j.logger.org.apache.commons','INFO,SCHED')
INSERT INTO log4j_conf(name,value) Values('log4j.appender.aCmdline.layout.ConversionPattern','[ %d [%t] %C{2}.%M():%L %x %-5p]: %m%n')
INSERT INTO log4j_conf(name,value) Values('log4j.appender.SCHED.layout','org.apache.log4j.PatternLayout')
INSERT INTO log4j_conf(name,value) Values('log4j.appender.aWeb.layout.ConversionPattern','[ %d [%t] %C{2}.%M():%L %x %-5p]: %m%n')
INSERT INTO log4j_conf(name,value) Values('log4j.logger.indexer.transbit.tbits.indexer','INFO,aWeb')
INSERT INTO log4j_conf(name,value) Values('log4j.appender.INDEX','transbit.tbits.common.TBitsFileAppender')
INSERT INTO log4j_conf(name,value) Values('log4j.appender.ORG.layout','org.apache.log4j.PatternLayout')
INSERT INTO log4j_conf(name,value) Values('log4j.logger.cmdline.transbit.tbits.scheduler','INFO,SCHED')

GO

INSERT INTO quartz_properties(name,value) Values('org.quartz.scheduler.instanceId','AUTO')
INSERT INTO quartz_properties(name,value) Values('org.quartz.scheduler.instanceName','TBitsQuartzScheduler')
INSERT INTO quartz_properties(name,value) Values('org.quartz.jobStore.tablePrefix','QRTZ_')
INSERT INTO quartz_properties(name,value) Values('org.quartz.jobStore.class','org.quartz.impl.jdbcjobstore.JobStoreTX')
INSERT INTO quartz_properties(name,value) Values('org.quartz.scheduler.rmi.registryPort','2098')
INSERT INTO quartz_properties(name,value) Values('org.quartz.threadPool.class','org.quartz.simpl.SimpleThreadPool')
INSERT INTO quartz_properties(name,value) Values('org.quartz.jobStore.useProperties','true')
INSERT INTO quartz_properties(name,value) Values('org.quartz.scheduler.rmi.registryHost','localhost')
INSERT INTO quartz_properties(name,value) Values('org.quartz.threadPool.threadPriority','5')
INSERT INTO quartz_properties(name,value) Values('org.quartz.jobStore.isClustered','false ')
INSERT INTO quartz_properties(name,value) Values('org.quartz.scheduler.rmi.createRegistry','true')
INSERT INTO quartz_properties(name,value) Values('org.quartz.scheduler.rmi.serverPort','0')
INSERT INTO quartz_properties(name,value) Values('org.quartz.scheduler.rmi.export','true')
INSERT INTO quartz_properties(name,value) Values('org.quartz.threadPool.threadCount','10')
INSERT INTO quartz_properties(name,value) Values('org.quartz.jobStore.driverDelegateClass','org.quartz.impl.jdbcjobstore.MSSQLDelegate')

Go
