INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.add.link_requests','Link Files')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.admin.volunteer','Volunteer')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.all.camel_case_request','File')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.myrequests.subscriber','Subscriber')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.view.update_request','Update File')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.view.transfer_request','Transfer File')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.all.camel_case_requests','Files')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.all.request_type','File Type')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.view.sort_request_history','Sort File History')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.all.my_requests','My Files')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.main.all.request_number','File #')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.myrequests.logger','Logger')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.all.request','file')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.view.request_history','File History')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.view.add_subrequest','Add Noting File')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.view.add_request','Add File')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.definition','File Management System')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.view.print_request_details','Print File Details')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.description','tBits is the next generation web-based file management system that combines the power of workflow, database systems, advance searching technology and convenience of email systems.')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.myrequests.due_date','Due Date')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.admin.assignee','Assignee')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.all.requests','files')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.view.request_details','File Details')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.all.camel_case_severity','Priority')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.myrequests.assignee','Assignee')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.view.subrequests','Noting files')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.all.new_request','New File')
