
delete rp
from roles_permissions rp
left OUTER JOIN ROLES R ON RP.SYS_ID=R.SYS_ID AND RP.ROLE_ID = R.ROLE_ID
WHERE R.ROLE_ID IS NULL

delete ru
from roles_USERS ru
left OUTER JOIN ROLES R ON RU.SYS_ID=R.SYS_ID AND RU.ROLE_ID = R.ROLE_ID
WHERE R.ROLE_ID IS NULL

--
--SELECT DISTINCT RP.SYS_ID,rP.ROLE_ID 
--INTO #tmp
--FROM ROLES_PERMISSIONS RP 
--LEFT OUTER JOIN  ROLES R ON RP.SYS_ID=R.SYS_ID AND RP.ROLE_ID = R.ROLE_ID
--WHERE R.ROLE_ID IS NULL
--
--DELETE FROM ROLES_PERMISSIONS
-- WHERE 
--    SYS_id IN (SELECT SYS_ID FROM #TMP WHERE ROLES_PERMISSIONS.ROLE_ID = ROLE_ID) 
--AND ROLE_ID IN (SELECT ROLE_ID FROM #TMP WHERE ROLES_PERMISSIONS.SYS_ID = SYS_ID) 
--GO
--
--drop table #tmp
--go
--SELECT DISTINCT RP.SYS_ID,rP.ROLE_ID 
--INTO #tmp
--FROM ROLES_users RP 
--LEFT OUTER JOIN  ROLES R ON RP.SYS_ID=R.SYS_ID AND RP.ROLE_ID = R.ROLE_ID
--WHERE R.ROLE_ID IS NULL
--
--DELETE FROM ROLES_users
-- WHERE 
--    SYS_id IN (SELECT SYS_ID FROM #TMP WHERE ROLES_users.ROLE_ID = ROLE_ID) 
--AND ROLE_ID IN (SELECT ROLE_ID FROM #TMP WHERE ROLES_users.SYS_ID = SYS_ID) 
--gO
--drop table #tmp
--GO
--
