INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.add.link_requests','Link Discussions')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.admin.volunteer','Volunteer')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.all.camel_case_request','Discussion')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.myrequests.subscriber','Subscriber')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.view.update_request','Update')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.view.transfer_request','Transfer Discussion')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.all.camel_case_requests','Discussions')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.all.request_type','Discussion Type')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.view.sort_request_history','Sort Discussion History')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.all.my_requests','My Discussions')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.main.all.request_number','ID #')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.myrequests.logger','Sender')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.all.request','discussion')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.view.request_history','Discussion History')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.view.add_subrequest','Add Action Item')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.view.add_request','Add Discussion')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.definition','Project Management System')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.view.print_request_details','Print Discussion Details')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.description','tBits is the next generation web-based project management system that combines the power of workflow, database systems, advance searching technology and convenience of email systems.')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.myrequests.due_date','Due Date')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.admin.assignee','Assignee')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.all.requests','discussions')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.view.request_details','Discussion Details')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.all.camel_case_severity','Priority')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.myrequests.assignee','Assignee')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.view.subrequests','Action Items')
INSERT INTO captions_properties(sys_id,name,value) Values('0','captions.all.new_request','New Discussion')
