//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tBitsOutlookPlugin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("tBitsOutlookPlugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;tbitsconf&gt;
        ///  &lt;users&gt;
        ///    &lt;user id=&quot;1&quot;&gt;
        ///      &lt;login&gt;root&lt;/login&gt;
        ///      &lt;firstName&gt;Root&lt;/firstName&gt;
        ///      &lt;lastName&gt;tBits&lt;/lastName&gt;
        ///      &lt;displayName&gt;Root&lt;/displayName&gt;
        ///    &lt;/user&gt;
        ///    &lt;user id=&quot;2&quot;&gt;
        ///      &lt;login&gt;uday&lt;/login&gt;
        ///      &lt;firstName&gt;Uday&lt;/firstName&gt;
        ///      &lt;lastName&gt;Kiran&lt;/lastName&gt;
        ///      &lt;displayName&gt;Uday&lt;/displayName&gt;
        ///    &lt;/user&gt;
        ///
        ///    &lt;user id=&quot;3&quot;&gt;
        ///      &lt;login&gt;ritesh&lt;/login&gt;
        ///      &lt;firstName&gt;Ritesh&lt;/firstName&gt;
        ///      &lt;lastName&gt;Tripathi&lt;/l [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BusinessAreaInfo {
            get {
                return ResourceManager.GetString("BusinessAreaInfo", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon c101 {
            get {
                object obj = ResourceManager.GetObject("c101", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap calendar {
            get {
                object obj = ResourceManager.GetObject("calendar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
