package billtracking.com.tbitsGlobal.shared;
import billtracking.com.tbitsGlobal.client.services.BillService;
import billtracking.com.tbitsGlobal.client.services.BillServiceAsync;

import com.google.gwt.core.client.GWT;

public interface IBillConstants  {

	
	public static final BillServiceAsync billService = GWT.create(BillService.class);
	
	//state info in DB
	public static final String process_table_Name="plugins_process_state_flow";
	public static final String plugin_name="lntBillTracking";
	
	public static final String bill_state_id = "stepid";
	public  static final String bill_process_id = "processid";
	
	//For LNT
	public static final String Bill_BusinessArea	="sys_id";
	public static final String Bill_Request	="request_id";
	public static final String Category	="category_id";
	//public static final String FlowStatus	="status_id";
	public static final String Priority	="severity_id";
	public static final String RequestType	="request_type_id";
	public static final String Logger	="logger_ids";
	public static final String Assignee	="assignee_ids";
	public static final String Subscribers	="subscriber_ids";
	public static final String To	="to_ids";
	public static final String Cc	="cc_ids";
	public static final String Subject	="subject";
	public static final String Description	="description";
	public static final String Private	="is_private";
	public static final String Parent	="parent_request_id";
	public static final String LastUpdateBy_	="user_id";
	public static final String _U	="max_action_id";
	public static final String PaymentDateasperPO	="due_datetime";
	public static final String SubmittedDate	="logged_datetime";
	public static final String LastUpdated	="lastupdated_datetime";
	public static final String HeaderDescription	="header_description";
	public static final String OtherAttachments	="attachments";
	public static final String Comments	="summary";
	public static final String Memo	="memo";
	public static final String append_interface	="append_interface";
	public static final String Notify	="notify";
	public static final String NotifyLogger	="notify_loggers";
	public static final String replied_to_action	="replied_to_action";
	public static final String LinkedRequests	="related_requests";
	public static final String Office	="office_id";
	public static final String SendSMS	="SendSMS";
	public static final String Project	="Project";
	public static final String VendorName	="Vendorname";
	public static final String PaymentType	="Paymenttype";
	public static final String PO_	="POnumber";
	public static final String PODate	="POdate";
	public static final String POQuantity	="POqnty";
	public static final String MaterialDescription	="Materialdescription";
	public static final String POValue	="POvalue";
	public static final String Buyer	="Buyer";
	public static final String Invoice_	="Invoiceno";
	public static final String InvoicedValue	="Invoicedvalue";
	public static final String InvoiceDate	="Invoicedate";
	public static final String InvoiceRecieptDate	="Recieptdate";
	public static final String GRN_	="grnno";
	public static final String GRN_Invoice_	     ="grnnoInvoiceno";
	public static final String QntyRejected	="Rejectedqnty";
	public static final String GRNDate	="grndate";
	public static final String QntyAaccepted	="Qntyaccepted";
	public static final String StoresI_C	="Stores";
	public static final String PEReco	="PErecommendation";
	public static final String SiteI_C	="Site";
	public static final String TargetDateofCompletion	="Targetdate";
	public static final String StoreI_CReco	="Storeicrecom";
	public static final String PackageManager	="Packmanager";
	public static final String SiteI_CDeecision	="Siteicdeci";
	public static final String PackageEngg	="PackEngg";
	public static final String PMreco	="PMrecomm";
	public static final String Other	="Other";
	public static final String OtherReco	="Otherrecomm";
	public static final String ActionByQA_C	="SiteQAaction";
	public static final String QAInputsProvided	="QAinput";
	public static final String TargetdateofQA	="TargetdateofQA";
	public static final String ActionbyStores	="Actionbystores";
	public static final String StoresInputsProvided	="Inputstostores";
	public static final String TargetforStores	="Targetforstores";
	public static final String CostController	="Costcontroller";
	public static final String CCReco	="CCrecomm";
	public static final String ExPackageEngg	="Expackengg";
	public static final String ExPEReco	="ExPErecomm";
	public static final String ExPackageMngr	="Expackmgr";
	public static final String ExPMReco	="ExPMrecomm";
	public static final String ProjectDir	="Projdir";
	public static final String PDDecision	="PDdeci";
	public static final String TargetDateofEx	="Targetdateofex";
	public static final String ServiceEntry_	="Serviceno";
	public static final String ServiceEntrryDate	="Servicedate";
	public static final String InvoicePassValue	="Invoicepassvalue";
	public static final String OtherExecutions	="Otherex";
	public static final String OtherExReco	="Otherexrecomm";
	public static final String PPM	="ppm";
	public static final String PPMReco	="ppmrecomm";
	public static final String CM	="cm";
	public static final String CMReco	="cmrecomm";
	public static final String PD	="pd";
	public static final String PDReco	="pdrecomm";
	//public static final String PaymentReq	="Paymentreq";
	public static final String PaymentRedDate	="Paymentreddate";
	public static final String PaymentReqValue	="Paymentvalue";
	public static final String SCMInvoicevalue	="scminvoicevalue";
	public static final String OtherSCM	="Otherscm";
	public static final String OtherSCMReco	="Otherscmrecomm";
	public static final String SCMTargetdate	="scmtargetdate";
	public static final String PaymentReleasedate	="Paymentreleasedate";
	public static final String Cheque_	="Chequeno";
	public static final String ChequeDate	="Chequedate";
	public static final String Amount	="faamount";
	public static final String GuaranteeDocreceiptdate	="Docrptdate";
	public static final String Stampdate	="Stampdate";
	public static final String GuaranteeDocdate	="Docdate";
	public static final String GuaranteeDocexpirydate	="Docexpirydate";
	public static final String Guaranteevalue	="Guaranteevalue";

	public static final String Enclosures	="Enclosures";
	public static final String SCMFlowStatus	="flowstatus";
	public static final String ExFlowstatus	="exflowstatus";
	public static final String FAFlowstatus	="faflowstatus";
	public static final String Statuswithdepartments	="Statuswithdepartments";

	public static final String SCMAckDate	         ="SCMAckDate";
	public static final String UserDeptAckDate	     ="UserDeptAckDate";
	public static final String SiteQAAckDate	     ="SiteQAAckDate";
	public static final String SiteStoresAckDate	 ="SiteStoresAckDate";
	public static final String ExecutionAckDate	     ="ExecutionAckDate";
	public static final String FinanceAckDate	     ="FinanceAckDate";


	//Type Fields
	public static final String Type_Category_Others	="pending";
	public static final String Type_Flow_Status_Pending	="Pending";
	public static final String Type_Flow_Status_Active	="Active";
	public static final String Type_Flow_Status_Closed	="Closed";
	public static final String Type_Flow_Status_Reopened	="Reopened";
	public static final String Type_Flow_Status_Suspended	="Suspended";
	public static final String Type_Priority_Low	="low";
	public static final String Type_Priority_Medium	="medium";
	public static final String Type_Priority_High	="high";
	public static final String Type_Priority_Critical	="critical";
	public static final String Type_Request_Type_Request	="request";
	public static final String Type_Request_Type_Question	="question";
	public static final String Type_Office__	="default";
	public static final String Type_Project_APPDCL	="APPDCL";
	public static final String Type_Project_Power	="DBPower";
	public static final String Type_Project_JP_Kharchana	="JPKHarchana";
	public static final String Type_Project_JP_Nigrie	="JPNigrie";
	public static final String Type_Project_Karadi	="Karadi";
	public static final String Type_Project_Malwa	="Malwa";
	public static final String Type_Project_None	="None";
	public static final String Type_Project_Raypura	="Raypura";
	public static final String Type_Project_Vemagiri	="Vemagiri";
	public static final String Type_Project_VISA_Power	="VISAPower";
	public static final String Type_Payment_Type_Advance_Payment_Against_Dispatch	="AdvancePaymentAgainstDispatch";
	public static final String Type_Payment_Type_Advance_Payment_Against_Drawing_Submission	="AdvancePaymentAgainstDrawingSubmission";
	public static final String Type_Payment_Type_Advance_Payment_Against_Order	="AdvancePaymentAgainstOrder";
	public static final String Type_Payment_Type_Advance_Payment_Against_Rawmaterials	="AdvancePaymentAgainstRawmaterials";
	public static final String Type_Payment_Type_Advance_Payment_Against_Readiness_of_item	="AdvancePaymentAgainstReadinessofitem";
	public static final String Type_Payment_Type_Advance_Payment_Against_receipt_of_Rawmaterials	="AdvancePaymentAgainstVendorsWork";
	public static final String Type_Payment_Type_None	="None";
	public static final String Type_Payment_Type_Retention_Payment_Against_Warranty	="RetentionPaymentAgainstWarranty";
	public static final String Type_Payment_Type_Service_Payment_Against_Erection	="ServicePaymentAgainstErection";
	public static final String Type_Payment_Type_Service_Payment_Against_Fabrication	="ServicePaymentAgainstFabrication";
	public static final String Type_Payment_Type_Service_Payment_Against_Mobilization	="ServicePaymentAgainstMobilization";
	public static final String Type_Payment_Type_Service_Payment_Against_No_load_Trail	="ServicePaymentAgainstNo_loadTrail";
	public static final String Type_Payment_Type_Supply_Payment_Against_Dispatch	="SupplyPaymentAgainstDispatch";
	public static final String Type_Payment_Type_Supply_Payment_Against_Material_at_site	="SupplyPaymentAgainstMaterialatsite";
	public static final String Type_PE_Reco_Approved	="Approved";
	public static final String Type_PE_Reco_NA	="NA";
	public static final String Type_PE_Reco_None	="None";
	public static final String Type_PE_Reco_Rejected	="Rejected";
	public static final String Type_Store_I_C_Reco_Approved	="Approved";
	public static final String Type_Store_I_C_Reco_NA	="NA";
	public static final String Type_Store_I_C_Reco_None	="None";
	public static final String Type_Store_I_C_Reco_Rejected	="Rejected";
	public static final String Type_Site_I_C_Deecision_Approved	="Approved";
	public static final String Type_Site_I_C_Deecision_None	="None";
	public static final String Type_Site_I_C_Deecision_Rejected	="Rejected";
	public static final String Type_PM_reco_Approved	="Approved";
	public static final String Type_PM_reco_NA	="NA";
	public static final String Type_PM_reco_None	="None";
	public static final String Type_PM_reco_Rejected	="Rejected";
	public static final String Type_Other_Reco_Approved	="Approved";
	public static final String Type_Other_Reco_NA	="NA";
	public static final String Type_Other_Reco_None	="None";
	public static final String Type_Other_Reco_Rejected	="Rejected";
	public static final String Type_Inputs_Provided_NA	="NA";
	public static final String Type_Inputs_Provided_No	="No";
	public static final String Type_Inputs_Provided_Yes	="Yes";
	public static final String Type_CC_Reco_Approved	="Approved";
	public static final String Type_CC_Reco_NA	="NA";
	public static final String Type_CC_Reco_None	="None";
	public static final String Type_CC_Reco_Rejected	="Rejected";
	public static final String Type_Ex_PM_Reco_Approved	="Approved";
	public static final String Type_Ex_PM_Reco_NA	="NA";
	public static final String Type_Ex_PM_Reco_None	="None";
	public static final String Type_Ex_PM_Reco_Rejected	="Rejected";
	public static final String Type_PD_Decision_Approved	="Approved";
	public static final String Type_PD_Decision_None	="None";
	public static final String Type_PD_Decision_Rejected	="Rejected";
	public static final String Type_Other_Ex_Reco_Approved	="Approved";
	public static final String Type_Other_Ex_Reco_NA	="NA";
	public static final String Type_Other_Ex_Reco_None	="None";
	public static final String Type_Other_Ex_Reco_Rejected	="Rejected";
	public static final String Type_PPM_Reco_Approved	="Approved";
	public static final String Type_PPM_Reco_NA	="NA";
	public static final String Type_PPM_Reco_None	="None";
	public static final String Type_PPM_Reco_Rejected	="Rejected";
	public static final String Type_CM_Reco_Approved	="Approved";
	public static final String Type_CM_Reco_NA	="NA";
	public static final String Type_CM_Reco_None	="None";
	public static final String Type_CM_Reco_Rejected	="Rejected";
	public static final String Type_PD_Reco_Approved	="Approved";
	public static final String Type_PD_Reco_NA	="NA";
	public static final String Type_PD_Reco_None	="None";
	public static final String Type_PD_Reco_Rejected	="Rejected";
	public static final String Type_Other_SCM_Reco_Approved	="Approved";
	public static final String Type_Other_SCM_Reco_NA	="NA";
	public static final String Type_Other_SCM_Reco_None	="None";
	public static final String Type_Other_SCM_Reco_Rejected	="Rejected";
	public static final String Type_Ex_Flow_status_Pending	="Pending";
	public static final String Type_Ex_Flow_status_Active	="Active";
	public static final String Type_Ex_Flow_status_Closed	="Closed";
	public static final String Type_Ex_Flow_status_Suspended	="Suspended";
	public static final String Type_FA_Flow_status_Pending	="Pending";
	public static final String Type_FA_Flow_status_Active	="Active";
	public static final String Type_FA_Flow_status_Closed	="Closed";
	public static final String Type_FA_Flow_status_Suspended	="Suspended";
	public static final String Type_Status_with_departments_Pendingwithexecution	="Pendingwithexecution";
	public static final String Type_Status_with_departments_PendingwithsiteQA	="PendingwithsiteQA";
	public static final String Type_Status_with_departments_Pendingwithsitestores	="Pendingwithsitestores";
	public static final String Type_Status_with_departments_Pendingwithuserdeprtment	="Pendingwithuserdeprtment";
	public static final String Type_Status_with_departments_Pendingwithscm	="Pendingwithscm";
	public static final String Type_Status_with_departments_Pendingwithfinance = "Pendingwithfinance";
	public static final String process_identification_table_Name = "plugins_process_identification_table";
	public static final String Type_Status_with_departments_Closed = "Closed";

	
	
	//Required Fields
	public static final String PaymentReq	="Payreq";
	public static final String AcceptedPO	="Accpo";
	public static final String Invoice_comm_	="Invoice";
	public static final String Invoice_Tax_	="Taxinv";
	public static final String LRCopy	="Lrcopy";
	public static final String PackingList	="Packlist";
	public static final String DeliveryChelan	="Deliverychelan";
	public static final String AckLRCopy	="Acklrcopy";
	public static final String Sitereceiptnote	="Siterptnote";
	public static final String MRIR	="mrir";
	public static final String SiteGRN	="Sitegrn";
	public static final String ServiceEntrysheet	="Serviceentrysheet";
	public static final String Measurementsheet	="Measurement";
	public static final String Attendancesheet	="Attendsheet";
	public static final String Vendortools	="Vendortools";
	public static final String Workmaninsurence	="Workmaninsurence";
	public static final String SpecsItems	="Specsitems";
	public static final String Drawings	="Drawings";
	public static final String POCopy	="pocopy";
	public static final String DispatchDoc	="Dispatchdoc";
	public static final String GRNofVendor	="grnno";
	public static final String TestCertificate	="Testcerti";
	public static final String Inspectioncertificate	="Inspectioncerti";
	public static final String InspectionReportcopy	="Inspectionreportcopy";
	public static final String Commissioningprotocolcopy	="Commissioningprotocolcopy";
	public static final String Guaranteeprotocolcopy	="Guaranteeprotocolcopy";
	public static final String DispatchCertificate	="Dispatchcerti";
	public static final String InsurenceCopy	="Insurencecopy";
	public static final String Submissioncertificate	="Submissioncerti";
	public static final String NoclaimsCertificate	="Noclaimscerti";
	public static final String Guaranteedoc1	="gdoc1";
	public static final String GuaranteeDoc2	="gdoc2";
	public static final String Guaranteedoc3	="gdoc3";
	public static final String GuaranteeDoc4	="gdoc4";
	
	
	//Received  fields
	public static String Rpayreq="Rpayreq";
	public static String RAccpo="RAccpo";
	public static String RInvoice="RInvoice";
	public static String RTaxinv="RTaxinv";
	public static String RLrcopy="RLrcopy";
	public static String RPacklist="RPacklist";
	public static String RDeliverychelan="RDeliverychelan";
	public static String RAcklrcopy="RAcklrcopy";
	public static String RSiterptnote="RSiterptnote";
	public static String Rmrir="Rmrir";
	public static String RSitegrn="RSitegrn";
	public static String RServiceentrysheet="RServiceentrysheet";
	public static String RMeasurement="RMeasurement";
	public static String RAttendsheet="RAttendsheet";
	public static String RVendortools="RVendortools";
	public static String RWorkmaninsurence="RWorkmaninsurence";
	public static String RSpecsitems="RSpecsitems";
	public static String RDrawings="RDrawings";
	public static String Rpocopy="Rpocopy";
	public static String RDispatchdoc="RDispatchdoc";
	public static String Rgrn="Rgrn";
	public static String RTestcerti="RTestcerti";
	public static String RInspectioncerti="RInspectioncerti";
	public static String RInspectionreportcopy="RInspectionreportcopy";
	public static String RCommissioningprotocolcopy="RCommissioningprotocolcopy";
	public static String RGuaranteeprotocolcopy="RGuaranteeprotocolcopy";
	public static String RDispatchcerti="RDispatchcerti";
	public static String RInsurencecopy="RInsurencecopy";
	public static String RSubmissioncerti="RSubmissioncerti";
	public static String RNoclaimscerti="RNoclaimscerti";
	public static String Rgdoc1="Rgdoc1";
	public static String Rgdoc2="Rgdoc2";
	public static String Rgdoc3="Rgdoc3";
	public static String Rgdoc4="Rgdoc4";







}
