-- Unable to Render DDL with DBMS_METADATA using internal generator.
CREATE TABLE ACTION_USERS
(
  SYS_ID NUMBER(10, 0) NOT NULL,
  REQUEST_ID NUMBER(10, 0) NOT NULL,
  ACTION_ID NUMBER(10, 0) NOT NULL,
  USER_TYPE_ID NUMBER(10, 0) NOT NULL,
  USER_ID NUMBER(10, 0) NOT NULL,
  ORDERING NUMBER(10, 0),
  IS_PRIMARY NUMBER(10, 0) NOT NULL
, CONSTRAINT PK_ACTION_USERS PRIMARY KEY
  (
    SYS_ID,
    REQUEST_ID,
    ACTION_ID,
    USER_TYPE_ID,
    USER_ID
  )
  ENABLE
)
  TABLESPACE "USERS"
  LOGGING 
  PCTFREE 10
  PCTUSED 40
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    FREELISTS 1
    FREELIST GROUPS 1
    BUFFER_POOL DEFAULT
  )
;

-- Unable to Render DDL with DBMS_METADATA using internal generator.
CREATE TABLE ACTIONS
(
  SYS_ID NUMBER(10, 0) NOT NULL,
  REQUEST_ID NUMBER(10, 0) NOT NULL,
  ACTION_ID NUMBER(10, 0) NOT NULL,
  CATEGORY_ID NUMBER(10, 0) NOT NULL,
  STATUS_ID NUMBER(10, 0) NOT NULL,
  SEVERITY_ID NUMBER(10, 0) NOT NULL,
  REQUEST_TYPE_ID NUMBER(10, 0) NOT NULL,
  SUBJECT NVARCHAR2(512) NOT NULL,
  DESCRIPTION CLOB NOT NULL,
  IS_PRIVATE NUMBER(1, 0) NOT NULL,
  PARENT_REQUEST_ID NUMBER(10, 0) NOT NULL,
  USER_ID NUMBER(10, 0) NOT NULL,
  DUE_DATETIME DATE,
  LOGGED_DATETIME DATE NOT NULL,
  LASTUPDATED_DATETIME DATE NOT NULL,
  HEADER_DESCRIPTION CLOB,
  ATTACHMENTS CLOB,
  SUMMARY CLOB,
  MEMO CLOB,
  APPEND_INTERFACE NUMBER(10, 0) NOT NULL,
  NOTIFY NUMBER(10, 0) NOT NULL,
  NOTIFY_LOGGERS NUMBER(1, 0) NOT NULL,
  REPLIED_TO_ACTION NUMBER(10, 0),
  OFFICE_ID NUMBER(10, 0)
, CONSTRAINT OK_ACTIONS PRIMARY KEY
  (
    SYS_ID,
    REQUEST_ID,
    ACTION_ID
  )
  ENABLE
)
  TABLESPACE "USERS"
  LOGGING 
  PCTFREE 10
  PCTUSED 40
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    FREELISTS 1
    FREELIST GROUPS 1
    BUFFER_POOL DEFAULT
  )
;

-- Unable to Render DDL with DBMS_METADATA using internal generator.
CREATE TABLE ACTIONS_EX
(
  SYS_ID NUMBER(10, 0) NOT NULL,
  REQUEST_ID NUMBER(10, 0) NOT NULL,
  ACTION_ID NUMBER(10, 0) NOT NULL,
  FIELD_ID NUMBER(10, 0) NOT NULL,
  BIT_VALUE NUMBER(1, 0),
  DATETIME_VALUE DATE,
  INT_VALUE NUMBER(10, 0),
  REAL_VALUE FLOAT(24),
  VARCHAR_VALUE NVARCHAR2(512),
  TEXT_VALUE CLOB,
  TYPE_VALUE NUMBER(10, 0)
, CONSTRAINT PK_ACTIONS_EX PRIMARY KEY
  (
    SYS_ID,
    REQUEST_ID,
    ACTION_ID,
    FIELD_ID
  )
  ENABLE
)
  TABLESPACE "USERS"
  LOGGING 
  PCTFREE 10
  PCTUSED 40
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    FREELISTS 1
    FREELIST GROUPS 1
    BUFFER_POOL DEFAULT
  )
;

-- Unable to Render DDL with DBMS_METADATA using internal generator.
CREATE TABLE BA_FORMS
(
  SYS_ID NUMBER(10, 0) NOT NULL,
  FORM_ID NUMBER(10, 0) NOT NULL,
  NAME VARCHAR2(128 BYTE) NOT NULL,
  TITLE VARCHAR2(512 BYTE),
  SHORTNAME VARCHAR2(64 BYTE),
  FORM_CONFIG CLOB
, CONSTRAINT PK_BA_FORMS PRIMARY KEY
  (
    SYS_ID,
    FORM_ID,
    NAME
  )
  ENABLE
)
  TABLESPACE "USERS"
  LOGGING 
  PCTFREE 10
  PCTUSED 40
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    FREELISTS 1
    FREELIST GROUPS 1
    BUFFER_POOL DEFAULT
  )
;

-- Unable to Render DDL with DBMS_METADATA using internal generator.
CREATE TABLE BA_MAIL_ACCOUNTS
(
  EMAIL_ID VARCHAR2(50 BYTE) NOT NULL,
  MAIL_SERVER VARCHAR2(100 BYTE) NOT NULL,
  BA_PREFIX VARCHAR2(100 BYTE) NOT NULL,
  PASSWARD VARCHAR2(50 BYTE) NOT NULL,
  PROTOCOL VARCHAR2(50 BYTE) DEFAULT 'pop3',
  PORT NUMBER(10, 0) DEFAULT 110,
  IS_ACTIVE NUMBER(1, 0) DEFAULT 0
)
  TABLESPACE "USERS"
  LOGGING 
  PCTFREE 10
  PCTUSED 40
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    FREELISTS 1
    FREELIST GROUPS 1
    BUFFER_POOL DEFAULT
  )
;

-- Unable to Render DDL with DBMS_METADATA using internal generator.
CREATE TABLE BA_RULES
(
  SYS_ID NUMBER(10, 0) NOT NULL,
  RULE_ID NUMBER(10, 0) NOT NULL,
  SEQUENCE_NO NUMBER(10, 0)
, CONSTRAINT PK_BA_RULES PRIMARY KEY
  (
    SYS_ID,
    RULE_ID
  )
  ENABLE
)
  TABLESPACE "USERS"
  LOGGING 
  PCTFREE 10
  PCTUSED 40
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    FREELISTS 1
    FREELIST GROUPS 1
    BUFFER_POOL DEFAULT
  )
;

-- Unable to Render DDL with DBMS_METADATA using internal generator.
CREATE TABLE BUSINESS_AREA_USERS
(
  SYS_ID NUMBER(10, 0) NOT NULL,
  USER_ID NUMBER(10, 0) NOT NULL,
  IS_ACTIVE NUMBER(10, 0)
, CONSTRAINT PK_BUSINESS_AREA_USERS PRIMARY KEY
  (
    SYS_ID,
    USER_ID
  )
  ENABLE
)
  TABLESPACE "USERS"
  LOGGING 
  PCTFREE 10
  PCTUSED 40
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    FREELISTS 1
    FREELIST GROUPS 1
    BUFFER_POOL DEFAULT
  )
;

-- Unable to Render DDL with DBMS_METADATA using internal generator.
CREATE TABLE BUSINESS_AREAS
(
  SYS_ID NUMBER(10, 0) NOT NULL,
  NAME NVARCHAR2(128) NOT NULL,
  DISPLAY_NAME NVARCHAR2(128) NOT NULL,
  EMAIL NVARCHAR2(255) NOT NULL,
  SYS_PREFIX NVARCHAR2(32) NOT NULL,
  DESCRIPTION NVARCHAR2(255) NOT NULL,
  TYPE NVARCHAR2(32) NOT NULL,
  LOCATION NVARCHAR2(32) NOT NULL,
  DATE_CREATED DATE NOT NULL,
  MAX_REQUEST_ID NUMBER(10, 0) NOT NULL,
  MAX_EMAIL_ACTIONS NUMBER(10, 0) NOT NULL,
  IS_EMAIL_ACTIVE NUMBER(1, 0) NOT NULL,
  IS_ACTIVE NUMBER(1, 0) NOT NULL,
  IS_PRIVATE NUMBER(1, 0) NOT NULL,
  SYS_CONFIG CLOB,
  FIELD_CONFIG CLOB
, CONSTRAINT PK_BUSINESS_AREAS PRIMARY KEY
  (
    SYS_ID
  )
  ENABLE
)
  TABLESPACE "USERS"
  LOGGING 
  PCTFREE 10
  PCTUSED 40
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    FREELISTS 1
    FREELIST GROUPS 1
    BUFFER_POOL DEFAULT
  )
;

-- Unable to Render DDL with DBMS_METADATA using internal generator.
CREATE TABLE DACTION_LOG
(
  SYS_ID NUMBER(10, 0) NOT NULL,
  REQUEST_ID NUMBER(10, 0) NOT NULL,
  ACTION_ID NUMBER(10, 0) NOT NULL,
  DACTION_LOG CLOB
)
  TABLESPACE "USERS"
  LOGGING 
  PCTFREE 10
  PCTUSED 40
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    FREELISTS 1
    FREELIST GROUPS 1
    BUFFER_POOL DEFAULT
  )
;

-- Unable to Render DDL with DBMS_METADATA using internal generator.
CREATE TABLE DATATYPES
(
  DATATYPE_ID NUMBER(10, 0) NOT NULL,
  NAME NVARCHAR2(255) NOT NULL,
  DESCRIPTION NVARCHAR2(255)
, CONSTRAINT PK_DATATYPES PRIMARY KEY
  (
    DATATYPE_ID
  )
  ENABLE
)
  TABLESPACE "USERS"
  LOGGING 
  PCTFREE 10
  PCTUSED 40
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    FREELISTS 1
    FREELIST GROUPS 1
    BUFFER_POOL DEFAULT
  )
;

-- Unable to Render DDL with DBMS_METADATA using internal generator.
CREATE TABLE DATETIME_FORMATS
(
  FORMAT_ID NUMBER(10, 0) NOT NULL,
  FORMAT NVARCHAR2(255) NOT NULL
, CONSTRAINT PK_DATETIME_FORMATS PRIMARY KEY
  (
    FORMAT_ID
  )
  ENABLE
)
  TABLESPACE "USERS"
  LOGGING 
  PCTFREE 10
  PCTUSED 40
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    FREELISTS 1
    FREELIST GROUPS 1
    BUFFER_POOL DEFAULT
  )
;

-- Unable to Render DDL with DBMS_METADATA using internal generator.
CREATE TABLE DEPENDENCIES
(
  SYS_ID NUMBER(10, 0) NOT NULL,
  DEP_ID NUMBER(10, 0) NOT NULL,
  DEP_NAME VARCHAR2(512 BYTE) NOT NULL,
  DEP_LEVEL VARCHAR2(30 BYTE) NOT NULL,
  DEP_TYPE VARCHAR2(30 BYTE) NOT NULL,
  DEP_CONFIG CLOB NOT NULL
, CONSTRAINT PK__DEPENDENCY_INFO__4203A4B5 PRIMARY KEY
  (
    SYS_ID,
    DEP_ID
  )
  ENABLE
)
  TABLESPACE "USERS"
  LOGGING 
  PCTFREE 10
  PCTUSED 40
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    FREELISTS 1
    FREELIST GROUPS 1
    BUFFER_POOL DEFAULT
  )
;

-- Unable to Render DDL with DBMS_METADATA using internal generator.
CREATE TABLE DEPENDENT_FIELDS
(
  SYS_ID NUMBER(10, 0) NOT NULL,
  DEP_ID NUMBER(10, 0) NOT NULL,
  FIELD_ID NUMBER(10, 0) NOT NULL,
  DEP_ROLE VARCHAR2(50 BYTE) NOT NULL
, CONSTRAINT PK__DEPENDENT_FIELDS__6F95653B PRIMARY KEY
  (
    SYS_ID,
    DEP_ID,
    FIELD_ID
  )
  ENABLE
)
  TABLESPACE "USERS"
  LOGGING 
  PCTFREE 10
  PCTUSED 40
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    FREELISTS 1
    FREELIST GROUPS 1
    BUFFER_POOL DEFAULT
  )
;

-- Unable to Render DDL with DBMS_METADATA using internal generator.
CREATE TABLE DISPLAY_GROUPS
(
  ID NUMBER(10, 0) NOT NULL,
  DISPLAY_NAME VARCHAR2(50 BYTE),
  DISPLAY_ORDER NUMBER(10, 0) DEFAULT 0,
  IS_ACTIVE NUMBER(10, 0) DEFAULT 1 NOT NULL
, CONSTRAINT PK_DISPLAY_GROUPS PRIMARY KEY
  (
    ID
  )
  ENABLE
)
  TABLESPACE "USERS"
  LOGGING 
  PCTFREE 10
  PCTUSED 40
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    FREELISTS 1
    FREELIST GROUPS 1
    BUFFER_POOL DEFAULT
  )
;

-- Unable to Render DDL with DBMS_METADATA using internal generator.
CREATE TABLE ESCALATION_CONDITIONS
(
  SYS_ID NUMBER(10, 0),
  SEVERITY_ID NUMBER(10, 0),
  SPAN NUMBER(10, 0)
)
  TABLESPACE "USERS"
  LOGGING 
  PCTFREE 10
  PCTUSED 40
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    FREELISTS 1
    FREELIST GROUPS 1
    BUFFER_POOL DEFAULT
  )
;

-- Unable to Render DDL with DBMS_METADATA using internal generator.
CREATE TABLE ESCALATION_HEIRARCHY
(
  SYS_ID NUMBER(10, 0),
  USER_ID NUMBER(10, 0),
  PARENT_USER_ID NUMBER(10, 0)
)
  TABLESPACE "USERS"
  LOGGING 
  PCTFREE 10
  PCTUSED 40
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    FREELISTS 1
    FREELIST GROUPS 1
    BUFFER_POOL DEFAULT
  )
;

-- Unable to Render DDL with DBMS_METADATA using internal generator.
CREATE TABLE ESCALATION_HISTORY
(
  SYS_ID NUMBER(10, 0),
  REQUEST_ID NUMBER(10, 0),
  LAST_ESCALATED_TIME DATE
)
  TABLESPACE "USERS"
  LOGGING 
  PCTFREE 10
  PCTUSED 40
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    FREELISTS 1
    FREELIST GROUPS 1
    BUFFER_POOL DEFAULT
  )
;

-- Unable to Render DDL with DBMS_METADATA using internal generator.
CREATE TABLE EXCLUSION_LIST
(
  SYS_ID NUMBER(10, 0) NOT NULL,
  USER_ID NUMBER(10, 0) NOT NULL,
  USER_TYPE_ID NUMBER(10, 0) NOT NULL
, CONSTRAINT PK_EXCLUSION_LIST PRIMARY KEY
  (
    SYS_ID,
    USER_ID,
    USER_TYPE_ID
  )
  ENABLE
)
  TABLESPACE "USERS"
  LOGGING 
  PCTFREE 10
  PCTUSED 40
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    FREELISTS 1
    FREELIST GROUPS 1
    BUFFER_POOL DEFAULT
  )
;

-- Unable to Render DDL with DBMS_METADATA using internal generator.
CREATE TABLE EXTERNAL_RESOURCES
(
  RESOURCE_ID NUMBER(10, 0) NOT NULL,
  RESOURCE_NAME VARCHAR2(128 BYTE),
  RESOURCE_DEF CLOB
, PRIMARY KEY
  (
    RESOURCE_ID
  )
  ENABLE
)
  TABLESPACE "USERS"
  LOGGING 
  PCTFREE 10
  PCTUSED 40
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    FREELISTS 1
    FREELIST GROUPS 1
    BUFFER_POOL DEFAULT
  )
;

ALTER TABLE EXTERNAL_RESOURCES
ADD UNIQUE
(
  RESOURCE_NAME
)
 ENABLE
;

-- Unable to Render DDL with DBMS_METADATA using internal generator.
CREATE TABLE FIELD_DESCRIPTORS
(
  SYS_ID NUMBER(10, 0) NOT NULL,
  FIELD_ID NUMBER(10, 0) NOT NULL,
  FIELD_DESCRIPTOR NVARCHAR2(32) NOT NULL,
  IS_PRIMARY NUMBER(1, 0) DEFAULT 0
, CONSTRAINT PK_FIELD_DESCRIPTORS PRIMARY KEY
  (
    SYS_ID,
    FIELD_ID,
    FIELD_DESCRIPTOR
  )
  ENABLE
)
  TABLESPACE "USERS"
  LOGGING 
  PCTFREE 10
  PCTUSED 40
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    FREELISTS 1
    FREELIST GROUPS 1
    BUFFER_POOL DEFAULT
  )
;

-- Unable to Render DDL with DBMS_METADATA using internal generator.
CREATE TABLE FIELDS
(
  SYS_ID NUMBER(10, 0) NOT NULL,
  FIELD_ID NUMBER(10, 0) NOT NULL,
  NAME NVARCHAR2(128) NOT NULL,
  DISPLAY_NAME NVARCHAR2(128) NOT NULL,
  DESCRIPTION NVARCHAR2(512) NOT NULL,
  DATA_TYPE_ID NUMBER(10, 0) NOT NULL,
  IS_ACTIVE NUMBER(1, 0) NOT NULL,
  IS_EXTENDED NUMBER(1, 0) NOT NULL,
  IS_PRIVATE NUMBER(1, 0) NOT NULL,
  TRACKING_OPTION NUMBER(10, 0) NOT NULL,
  PERMISSION NUMBER(10, 0) NOT NULL,
  REGEX NVARCHAR2(1024),
  IS_DEPENDENT NUMBER(1, 0) DEFAULT 0,
  DISPLAY_ORDER NUMBER(10, 0) DEFAULT 0,
  DISPLAY_GROUP NUMBER(10, 0) DEFAULT 1
, CONSTRAINT PK_FIELDS PRIMARY KEY
  (
    SYS_ID,
    FIELD_ID
  )
  ENABLE
)
  TABLESPACE "USERS"
  LOGGING 
  PCTFREE 10
  PCTUSED 40
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    FREELISTS 1
    FREELIST GROUPS 1
    BUFFER_POOL DEFAULT
  )
;

-- Unable to Render DDL with DBMS_METADATA using internal generator.
CREATE TABLE HOLIDAYS_LIST
(
  OFFICE NVARCHAR2(255) NOT NULL,
  HOLIDAY_DATE NVARCHAR2(50) NOT NULL,
  OFFICE_ZONE NVARCHAR2(50) NOT NULL,
  DESCRIPTION VARCHAR2(512 BYTE)
)
  TABLESPACE "USERS"
  LOGGING 
  PCTFREE 10
  PCTUSED 40
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    FREELISTS 1
    FREELIST GROUPS 1
    BUFFER_POOL DEFAULT
  )
;

-- Unable to Render DDL with DBMS_METADATA using internal generator.
CREATE TABLE JOB_DEFINITIONS
(
  JOB_ID NUMBER(10, 0) NOT NULL,
  JOB_USER_ID NUMBER(10, 0) NOT NULL,
  JOB_CRITERIA CLOB NOT NULL,
  JOB_MONTH NUMBER(5, 0) NOT NULL,
  JOB_DATE NUMBER(5, 0) NOT NULL,
  JOB_DAY NUMBER(5, 0) NOT NULL,
  JOB_HOUR NUMBER(5, 0) NOT NULL,
  JOB_MINUTE NUMBER(5, 0) NOT NULL
, CONSTRAINT PK_JOB_DEFINITIONS PRIMARY KEY
  (
    JOB_ID
  )
  ENABLE
)
  TABLESPACE "USERS"
  LOGGING 
  PCTFREE 10
  PCTUSED 40
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    FREELISTS 1
    FREELIST GROUPS 1
    BUFFER_POOL DEFAULT
  )
;

-- Unable to Render DDL with DBMS_METADATA using internal generator.
CREATE TABLE JOB_NOTIFIERS
(
  JOB_ID NUMBER(10, 0) NOT NULL,
  USER_ID NUMBER(10, 0) NOT NULL
, CONSTRAINT PK_JOB_NOTIFIERS PRIMARY KEY
  (
    JOB_ID,
    USER_ID
  )
  ENABLE
)
  TABLESPACE "USERS"
  LOGGING 
  PCTFREE 10
  PCTUSED 40
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    FREELISTS 1
    FREELIST GROUPS 1
    BUFFER_POOL DEFAULT
  )
;

-- Unable to Render DDL with DBMS_METADATA using internal generator.
CREATE TABLE MAIL_LIST_USERS
(
  MAIL_LIST_ID NUMBER(10, 0) NOT NULL,
  USER_ID NUMBER(10, 0) NOT NULL
)
  TABLESPACE "USERS"
  LOGGING 
  PCTFREE 10
  PCTUSED 40
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    FREELISTS 1
    FREELIST GROUPS 1
    BUFFER_POOL DEFAULT
  )
;

-- Unable to Render DDL with DBMS_METADATA using internal generator.
CREATE TABLE MSG_FORMAT
(
  MSG_FORMAT_ID NUMBER(10, 0) NOT NULL,
  MSG_TEMPLATE CLOB NOT NULL,
  SYS_ID NUMBER(10, 0) NOT NULL
)
  TABLESPACE "USERS"
  LOGGING 
  PCTFREE 10
  PCTUSED 40
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    FREELISTS 1
    FREELIST GROUPS 1
    BUFFER_POOL DEFAULT
  )
;

-- Unable to Render DDL with DBMS_METADATA using internal generator.
CREATE TABLE PERMISSIONS
(
  PERMISSION NUMBER(10, 0) NOT NULL,
  PADD NUMBER(10, 0),
  PCHANGE NUMBER(10, 0),
  PVIEW NUMBER(10, 0)
, CONSTRAINT PK_PERMISSIONS PRIMARY KEY
  (
    PERMISSION
  )
  ENABLE
)
  TABLESPACE "USERS"
  LOGGING 
  PCTFREE 10
  PCTUSED 40
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    FREELISTS 1
    FREELIST GROUPS 1
    BUFFER_POOL DEFAULT
  )
;

-- Unable to Render DDL with DBMS_METADATA using internal generator.
CREATE TABLE POST_PROCESS_RULES
(
  RULE_ID NUMBER(10, 0) NOT NULL,
  USER_ID NUMBER(10, 0) NOT NULL,
  SYS_ID NUMBER(10, 0) NOT NULL,
  PRIORITY NUMBER(10, 0) NOT NULL,
  XML_STRING CLOB NOT NULL,
  DESCRIPTION CLOB NOT NULL,
  ENABLED NUMBER(1, 0) NOT NULL
, CONSTRAINT PK_POST_PROCESS_RULES PRIMARY KEY
  (
    RULE_ID
  )
  ENABLE
)
  TABLESPACE "USERS"
  LOGGING 
  PCTFREE 10
  PCTUSED 40
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    FREELISTS 1
    FREELIST GROUPS 1
    BUFFER_POOL DEFAULT
  )
;

-- Unable to Render DDL with DBMS_METADATA using internal generator.
CREATE TABLE RELATED_REQUESTS
(
  PRIMARY_SYS_PREFIX NVARCHAR2(64) NOT NULL,
  PRIMARY_REQUEST_ID NUMBER(10, 0) NOT NULL,
  PRIMARY_ACTION_ID NUMBER(10, 0) DEFAULT 0 NOT NULL,
  RELATED_SYS_PREFIX NVARCHAR2(64) NOT NULL,
  RELATED_REQUEST_ID NUMBER(10, 0) NOT NULL,
  RELATED_ACTION_ID NUMBER(10, 0) DEFAULT 0 NOT NULL
, CONSTRAINT PK_RELATED_REQUESTS PRIMARY KEY
  (
    PRIMARY_SYS_PREFIX,
    PRIMARY_REQUEST_ID,
    PRIMARY_ACTION_ID,
    RELATED_SYS_PREFIX,
    RELATED_REQUEST_ID,
    RELATED_ACTION_ID
  )
  ENABLE
)
  TABLESPACE "USERS"
  LOGGING 
  PCTFREE 10
  PCTUSED 40
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    FREELISTS 1
    FREELIST GROUPS 1
    BUFFER_POOL DEFAULT
  )
;

-- Unable to Render DDL with DBMS_METADATA using internal generator.
CREATE TABLE REQUEST_USERS
(
  SYS_ID NUMBER(10, 0) NOT NULL,
  REQUEST_ID NUMBER(10, 0) NOT NULL,
  USER_TYPE_ID NUMBER(10, 0) NOT NULL,
  USER_ID NUMBER(10, 0) NOT NULL,
  ORDERING NUMBER(10, 0),
  IS_PRIMARY NUMBER(1, 0) NOT NULL
, CONSTRAINT PK_REQUEST_USERS PRIMARY KEY
  (
    SYS_ID,
    REQUEST_ID,
    USER_TYPE_ID,
    USER_ID
  )
  ENABLE
)
  TABLESPACE "USERS"
  LOGGING 
  PCTFREE 10
  PCTUSED 40
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    FREELISTS 1
    FREELIST GROUPS 1
    BUFFER_POOL DEFAULT
  )
;

-- Unable to Render DDL with DBMS_METADATA using internal generator.
CREATE TABLE REQUESTS
(
  SYS_ID NUMBER(10, 0) NOT NULL,
  REQUEST_ID NUMBER(10, 0) NOT NULL,
  CATEGORY_ID NUMBER(10, 0) NOT NULL,
  STATUS_ID NUMBER(10, 0) NOT NULL,
  SEVERITY_ID NUMBER(10, 0) NOT NULL,
  REQUEST_TYPE_ID NUMBER(10, 0) NOT NULL,
  SUBJECT NVARCHAR2(512) NOT NULL,
  DESCRIPTION CLOB NOT NULL,
  IS_PRIVATE NUMBER(1, 0) NOT NULL,
  PARENT_REQUEST_ID NUMBER(10, 0) NOT NULL,
  USER_ID NUMBER(10, 0) NOT NULL,
  MAX_ACTION_ID NUMBER(10, 0) NOT NULL,
  DUE_DATETIME DATE,
  LOGGED_DATETIME DATE NOT NULL,
  LASTUPDATED_DATETIME DATE NOT NULL,
  HEADER_DESCRIPTION CLOB,
  ATTACHMENTS CLOB,
  SUMMARY CLOB,
  MEMO CLOB,
  APPEND_INTERFACE NUMBER(10, 0) NOT NULL,
  NOTIFY NUMBER(10, 0) NOT NULL,
  NOTIFY_LOGGERS NUMBER(1, 0) NOT NULL,
  REPLIED_TO_ACTION NUMBER(10, 0),
  OFFICE_ID NUMBER(10, 0) DEFAULT 0
, CONSTRAINT PK_REQUESTS PRIMARY KEY
  (
    SYS_ID,
    REQUEST_ID
  )
  ENABLE
)
  TABLESPACE "USERS"
  LOGGING 
  PCTFREE 10
  PCTUSED 40
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    FREELISTS 1
    FREELIST GROUPS 1
    BUFFER_POOL DEFAULT
  )
;

-- Unable to Render DDL with DBMS_METADATA using internal generator.
CREATE TABLE REQUESTS_EX
(
  SYS_ID NUMBER(10, 0) NOT NULL,
  REQUEST_ID NUMBER(10, 0) NOT NULL,
  FIELD_ID NUMBER(10, 0) NOT NULL,
  BIT_VALUE NUMBER(1, 0),
  DATETIME_VALUE DATE,
  INT_VALUE NUMBER(10, 0),
  REAL_VALUE FLOAT(24),
  VARCHAR_VALUE NVARCHAR2(512),
  TEXT_VALUE CLOB,
  TYPE_VALUE NUMBER(10, 0)
, CONSTRAINT PK_REQUESTS_EX PRIMARY KEY
  (
    SYS_ID,
    REQUEST_ID,
    FIELD_ID
  )
  ENABLE
)
  TABLESPACE "USERS"
  LOGGING 
  PCTFREE 10
  PCTUSED 40
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    FREELISTS 1
    FREELIST GROUPS 1
    BUFFER_POOL DEFAULT
  )
;

-- Unable to Render DDL with DBMS_METADATA using internal generator.
CREATE TABLE ROLES
(
  SYS_ID NUMBER(10, 0) NOT NULL,
  ROLE_ID NUMBER(10, 0) NOT NULL,
  ROLENAME NVARCHAR2(50) NOT NULL,
  DESCRIPTION NVARCHAR2(250) NOT NULL
, CONSTRAINT PK_ROLES PRIMARY KEY
  (
    SYS_ID,
    ROLE_ID
  )
  ENABLE
)
  TABLESPACE "USERS"
  LOGGING 
  PCTFREE 10
  PCTUSED 40
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    FREELISTS 1
    FREELIST GROUPS 1
    BUFFER_POOL DEFAULT
  )
;

-- Unable to Render DDL with DBMS_METADATA using internal generator.
CREATE TABLE ROLES_PERMISSIONS
(
  SYS_ID NUMBER(10, 0) NOT NULL,
  ROLE_ID NUMBER(10, 0) NOT NULL,
  FIELD_ID NUMBER(10, 0) NOT NULL,
  GPERMISSIONS NUMBER(5, 0) NOT NULL,
  DPERMISSIONS NUMBER(5, 0) NOT NULL
, CONSTRAINT PK_ROLES_PERMISSIONS PRIMARY KEY
  (
    SYS_ID,
    ROLE_ID,
    FIELD_ID
  )
  ENABLE
)
  TABLESPACE "USERS"
  LOGGING 
  PCTFREE 10
  PCTUSED 40
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    FREELISTS 1
    FREELIST GROUPS 1
    BUFFER_POOL DEFAULT
  )
;

-- Unable to Render DDL with DBMS_METADATA using internal generator.
CREATE TABLE ROLES_USERS
(
  SYS_ID NUMBER(10, 0) NOT NULL,
  ROLE_ID NUMBER(10, 0) NOT NULL,
  USER_ID NUMBER(10, 0) NOT NULL,
  IS_ACTIVE NUMBER(1, 0) DEFAULT 1
, CONSTRAINT PK_ROLES_USERS PRIMARY KEY
  (
    SYS_ID,
    ROLE_ID,
    USER_ID
  )
  ENABLE
)
  TABLESPACE "USERS"
  LOGGING 
  PCTFREE 10
  PCTUSED 40
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    FREELISTS 1
    FREELIST GROUPS 1
    BUFFER_POOL DEFAULT
  )
;

-- Unable to Render DDL with DBMS_METADATA using internal generator.
CREATE TABLE NOTIFICATION_RULES
(
  NOTIFICATION_ID NUMBER(10, 0) NOT NULL,
  NAME NVARCHAR2(64) NOT NULL,
  DISPLAY_NAME NVARCHAR2(128) NOT NULL,
  RULES_CONFIG CLOB NOT NULL
, CONSTRAINT PK_NOTIFICATION_RULES PRIMARY KEY
  (
    NOTIFICATION_ID
  )
  ENABLE
)
  TABLESPACE "USERS"
  LOGGING 
  PCTFREE 10
  PCTUSED 40
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    FREELISTS 1
    FREELIST GROUPS 1
    BUFFER_POOL DEFAULT
  )
;

-- Unable to Render DDL with DBMS_METADATA using internal generator.
CREATE TABLE SMS_LOG
(
  REQUEST_ID NUMBER(10, 0) NOT NULL,
  SYS_ID NUMBER(10, 0) NOT NULL,
  CELL_NO CLOB NOT NULL,
  DATE_ DATE NOT NULL,
  USER_ID NUMBER(10, 0) NOT NULL,
  ACTION_ID NUMBER(10, 0) NOT NULL
)
  TABLESPACE "USERS"
  LOGGING 
  PCTFREE 10
  PCTUSED 40
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    FREELISTS 1
    FREELIST GROUPS 1
    BUFFER_POOL DEFAULT
  )
;

-- Unable to Render DDL with DBMS_METADATA using internal generator.
CREATE TABLE SUPER_USERS
(
  USER_ID NUMBER(10, 0) NOT NULL,
  IS_ACTIVE NUMBER(1, 0) NOT NULL
, CONSTRAINT PK_SUPER_USERS PRIMARY KEY
  (
    USER_ID
  )
  ENABLE
)
  TABLESPACE "USERS"
  LOGGING 
  PCTFREE 10
  PCTUSED 40
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    FREELISTS 1
    FREELIST GROUPS 1
    BUFFER_POOL DEFAULT
  )
;

-- Unable to Render DDL with DBMS_METADATA using internal generator.
CREATE TABLE TRACKING_OPTIONS
(
  TRACKING_OPTION_ID NUMBER(10, 0) NOT NULL,
  DESCRIPTION VARCHAR2(512 BYTE) NOT NULL
, CONSTRAINT PK_TRACKING_OPTIONS PRIMARY KEY
  (
    TRACKING_OPTION_ID
  )
  ENABLE
)
  TABLESPACE "USERS"
  LOGGING 
  PCTFREE 10
  PCTUSED 40
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    FREELISTS 1
    FREELIST GROUPS 1
    BUFFER_POOL DEFAULT
  )
;

-- Unable to Render DDL with DBMS_METADATA using internal generator.
CREATE TABLE TRANSFERRED_REQUESTS
(
  SOURCE_PREFIX VARCHAR2(50 BYTE) NOT NULL,
  SOURCE_REQUEST_ID NUMBER(10, 0) NOT NULL,
  TARGET_PREFIX VARCHAR2(50 BYTE),
  TARGET_REQUEST_ID NUMBER(10, 0)
, CONSTRAINT PK_TRANSFERRED_REQUESTS PRIMARY KEY
  (
    SOURCE_PREFIX,
    SOURCE_REQUEST_ID
  )
  ENABLE
)
  TABLESPACE "USERS"
  LOGGING 
  PCTFREE 10
  PCTUSED 40
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    FREELISTS 1
    FREELIST GROUPS 1
    BUFFER_POOL DEFAULT
  )
;

-- Unable to Render DDL with DBMS_METADATA using internal generator.
CREATE GLOBAL TEMPORARY TABLE TT_ACTIONTMP
(
  SYS_ID NUMBER(10, 0) NOT NULL,
  REQUEST_ID NUMBER(10, 0) NOT NULL,
  ACTION_ID NUMBER(10, 0) NOT NULL,
  STATUS_ID NUMBER(10, 0) NOT NULL,
  CATEGORY_ID NUMBER(10, 0) NOT NULL,
  REQUEST_TYPE_ID NUMBER(10, 0) NOT NULL,
  SEVERITY_ID NUMBER(10, 0) NOT NULL,
  USER_ID NUMBER(10, 0) NOT NULL,
  LOGGED_DATETIME DATE NOT NULL,
  LASTUPDATED_DATETIME DATE NOT NULL
)
ON COMMIT DELETE ROWS
;

