update current_version set systype = 'dms'
INSERT INTO captions_properties (sys_id,name,value) VALUES (0,'captions.add.link_requests','Link Documents')
INSERT INTO captions_properties (sys_id,name,value) VALUES (0,'captions.admin.assignee','Assignee')
INSERT INTO captions_properties (sys_id,name,value) VALUES (0,'captions.admin.volunteer','Volunteer')
INSERT INTO captions_properties (sys_id,name,value) VALUES (0,'captions.all.camel_case_request','Document')
INSERT INTO captions_properties (sys_id,name,value) VALUES (0,'captions.all.camel_case_requests','Documents')
INSERT INTO captions_properties (sys_id,name,value) VALUES (0,'captions.all.camel_case_severity','Priority')
INSERT INTO captions_properties (sys_id,name,value) VALUES (0,'captions.all.my_requests','My Documents')
INSERT INTO captions_properties (sys_id,name,value) VALUES (0,'captions.all.new_request','New Document')
INSERT INTO captions_properties (sys_id,name,value) VALUES (0,'captions.all.request','document')
INSERT INTO captions_properties (sys_id,name,value) VALUES (0,'captions.all.request_type','Document Type')
INSERT INTO captions_properties (sys_id,name,value) VALUES (0,'captions.all.requests','documents')
INSERT INTO captions_properties (sys_id,name,value) VALUES (0,'captions.definition','Document Management and Project Collaboration Suite')
INSERT INTO captions_properties (sys_id,name,value) VALUES (0,'captions.description','tBits is the next generation web-based Document Management and Project Collaboration Suite that combines the power of workflow, database systems, advance searching technology and convenience of email systems.')
INSERT INTO captions_properties (sys_id,name,value) VALUES (0,'captions.main.all.request_number','Document #')
INSERT INTO captions_properties (sys_id,name,value) VALUES (0,'captions.myrequests.assignee','Assignee')
INSERT INTO captions_properties (sys_id,name,value) VALUES (0,'captions.myrequests.due_date','Due Date')
INSERT INTO captions_properties (sys_id,name,value) VALUES (0,'captions.myrequests.logger','Logger')
INSERT INTO captions_properties (sys_id,name,value) VALUES (0,'captions.myrequests.subscriber','Subscriber')
INSERT INTO captions_properties (sys_id,name,value) VALUES (0,'captions.view.add_request','Add Document')
INSERT INTO captions_properties (sys_id,name,value) VALUES (0,'captions.view.add_subrequest','Add Subrequest')
INSERT INTO captions_properties (sys_id,name,value) VALUES (0,'captions.view.print_request_details','Print Document Details')
INSERT INTO captions_properties (sys_id,name,value) VALUES (0,'captions.view.request_details','Document Details')
INSERT INTO captions_properties (sys_id,name,value) VALUES (0,'captions.view.request_history','Document History')
INSERT INTO captions_properties (sys_id,name,value) VALUES (0,'captions.view.sort_request_history','Sort Document History')
INSERT INTO captions_properties (sys_id,name,value) VALUES (0,'captions.view.subrequests','Subrequests')
INSERT INTO captions_properties (sys_id,name,value) VALUES (0,'captions.view.transfer_request','Transfer Document')
INSERT INTO captions_properties (sys_id,name,value) VALUES (0,'captions.view.update_request','Update Document')
INSERT INTO captions_properties(sys_id,name,value) Values(0,'captions.all.my_reports', 'My Reports')
INSERT INTO captions_properties(sys_id,name,value) Values(0,'captions.view.update_summary', 'Update Summary')
INSERT INTO captions_properties(sys_id,name,value) Values(0,'captions.view.add_summary', 'Add Summary')

GO
