//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xpress03form.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xpress03form.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;tbitsconf&gt;
        ///&lt;users&gt;
        ///&lt;user id=&quot;50029&quot;&gt;
        ///&lt;login&gt;hyperlink&lt;/login&gt;
        ///&lt;first_name&gt;hyperlink&lt;/first_name&gt;
        ///&lt;last_name&gt;hyperlink&lt;/last_name&gt;
        ///&lt;email_id&gt;hyperlink&lt;/email_id&gt;
        ///&lt;default_BA&gt;TBits&lt;/default_BA&gt;
        ///&lt;/user&gt;
        ///&lt;user id=&quot;50065&quot;&gt;
        ///&lt;login&gt;mgnr&lt;/login&gt;
        ///&lt;first_name&gt;mgnr&lt;/first_name&gt;
        ///&lt;last_name&gt;mgnr&lt;/last_name&gt;
        ///&lt;email_id&gt;mgnr&lt;/email_id&gt;
        ///&lt;default_BA&gt;TBits&lt;/default_BA&gt;
        ///&lt;/user&gt;
        ///&lt;user id=&quot;50103&quot;&gt;
        ///&lt;login&gt;dont&lt;/login&gt;
        ///&lt;first_name&gt;dont&lt;/first_name&gt;
        ///&lt;last_name&gt;dont&lt;/last_n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BAXMLInfo {
            get {
                return ResourceManager.GetString("BAXMLInfo", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon startserver {
            get {
                object obj = ResourceManager.GetObject("startserver", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
